<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Endpoints\Security_Analytics;

use Open_Search\Endpoints\Abstract_Endpoint;
/**
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Search_Finding_Correlations extends Abstract_Endpoint
{
    public function get_uri(): string
    {
        return '/_plugins/_security_analytics/findings/correlate';
    }
    public function get_param_whitelist(): array
    {
        return ['detector_type', 'finding', 'nearby_findings', 'time_window', 'pretty', 'human', 'error_trace', 'source', 'filter_path'];
    }
    public function get_method(): string
    {
        return 'GET';
    }
}