<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Endpoints\Ltr;

use Open_Search\Endpoints\Abstract_Endpoint;
use Open_Search\Exception\RuntimeException;
/**
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Add_Features_To_Set_By_Query extends Abstract_Endpoint
{
    protected $name;
    protected $query;
    protected $store;
    public function get_uri(): string
    {
        if (!isset($this->name) || $this->name === '') {
            throw new RuntimeException('name is required for add_features_to_set_by_query');
        }
        $name = rawurlencode((string) $this->name);
        if (!isset($this->query) || $this->query === '') {
            throw new RuntimeException('query is required for add_features_to_set_by_query');
        }
        $query = rawurlencode((string) $this->query);
        $store = $this->store ? rawurlencode((string) $this->store) : null;
        if (isset($store)) {
            return "/_ltr/{$store}/_featureset/{$name}/_addfeatures/{$query}";
        }
        return "/_ltr/_featureset/{$name}/_addfeatures/{$query}";
    }
    public function get_param_whitelist(): array
    {
        return ['merge', 'routing', 'version', 'pretty', 'human', 'error_trace', 'source', 'filter_path'];
    }
    public function get_method(): string
    {
        return 'POST';
    }
    public function set_name($name): static
    {
        if (is_null($name)) {
            return $this;
        }
        $this->name = $name;
        return $this;
    }
    public function set_query($query): static
    {
        if (is_null($query)) {
            return $this;
        }
        $this->query = $query;
        return $this;
    }
    public function set_store($store): static
    {
        if (is_null($store)) {
            return $this;
        }
        $this->store = $store;
        return $this;
    }
}