<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Endpoints\Ltr;

use Open_Search\Endpoints\Abstract_Endpoint;
use Open_Search\Exception\RuntimeException;
/**
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Create_Model extends Abstract_Endpoint
{
    protected $store;
    public function get_uri(): string
    {
        if (!isset($this->id) || $this->id === '') {
            throw new RuntimeException('id is required for create_model');
        }
        $id = rawurlencode((string) $this->id);
        $store = $this->store ? rawurlencode((string) $this->store) : null;
        if (isset($store)) {
            return "/_ltr/{$store}/_model/{$id}";
        }
        return "/_ltr/_model/{$id}";
    }
    public function get_param_whitelist(): array
    {
        return ['routing', 'pretty', 'human', 'error_trace', 'source', 'filter_path'];
    }
    public function get_method(): string
    {
        return 'PUT';
    }
    public function set_body($body): static
    {
        if (is_null($body)) {
            return $this;
        }
        $this->body = $body;
        return $this;
    }
    public function set_store($store): static
    {
        if (is_null($store)) {
            return $this;
        }
        $this->store = $store;
        return $this;
    }
}