<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Endpoints\Notifications;

use Open_Search\Endpoints\Abstract_Endpoint;
use Open_Search\Exception\RuntimeException;
/**
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Get_Config extends Abstract_Endpoint
{
    protected $config_id;
    public function get_uri(): string
    {
        $config_id = $this->config_id ? rawurlencode((string) $this->config_id) : null;
        if (isset($config_id)) {
            return "/_plugins/_notifications/configs/{$config_id}";
        }
        throw new RuntimeException('Missing parameter for the endpoint notifications.get_config');
    }
    public function get_param_whitelist(): array
    {
        return ['pretty', 'human', 'error_trace', 'source', 'filter_path'];
    }
    public function get_method(): string
    {
        return 'GET';
    }
    public function set_config_id($config_id): static
    {
        if (is_null($config_id)) {
            return $this;
        }
        $this->config_id = $config_id;
        return $this;
    }
}