<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Endpoints;

use Open_Search\Exception\RuntimeException;
/**
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Create_Pit extends Abstract_Endpoint
{
    public function get_uri(): string
    {
        if (!isset($this->index) || $this->index === '') {
            throw new RuntimeException('index is required for create_pit');
        }
        $index = rawurlencode($this->index);
        return "/{$index}/_search/point_in_time";
    }
    public function get_param_whitelist(): array
    {
        return ['allow_partial_pit_creation', 'expand_wildcards', 'keep_alive', 'preference', 'routing', 'pretty', 'human', 'error_trace', 'source', 'filter_path'];
    }
    public function get_method(): string
    {
        return 'POST';
    }
}