<?php

declare (strict_types=1);
/**
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * OpenSearch PHP client
 *
 * @link      https://github.com/opensearch-project/opensearch-php/
 * @copyright Copyright (c) Elasticsearch B.V (https://www.elastic.co)
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 * @license   https://www.gnu.org/licenses/lgpl-2.1.html GNU Lesser General Public License, Version 2.1
 *
 * Licensed to Elasticsearch B.V under one or more agreements.
 * Elasticsearch B.V licenses this file to you under the Apache 2.0 License or
 * the GNU Lesser General Public License, Version 2.1, at your option.
 * See the LICENSE file in the project root for more information.
 */
namespace Open_Search\Endpoints;

/**
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Scroll extends Abstract_Endpoint
{
    protected $scroll_id;
    public function get_uri(): string
    {
        $scroll_id = $this->scroll_id ? rawurlencode((string) $this->scroll_id) : null;
        if (isset($scroll_id)) {
            @trigger_error('A scroll id can be quite large and should be specified as part of the body', E_USER_DEPRECATED);
            return "/_search/scroll/{$scroll_id}";
        }
        return '/_search/scroll';
    }
    public function get_param_whitelist(): array
    {
        return ['rest_total_hits_as_int', 'scroll', 'scroll_id', 'pretty', 'human', 'error_trace', 'source', 'filter_path'];
    }
    public function get_method(): string
    {
        return isset($this->body) ? 'POST' : 'GET';
    }
    public function set_body($body): static
    {
        if (is_null($body)) {
            return $this;
        }
        $this->body = $body;
        return $this;
    }
    public function set_scroll_id($scroll_id): static
    {
        if (is_null($scroll_id)) {
            return $this;
        }
        $this->scroll_id = $scroll_id;
        return $this;
    }
}