<?php

declare (strict_types=1);
/**
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * OpenSearch PHP client
 *
 * @link      https://github.com/opensearch-project/opensearch-php/
 * @copyright Copyright (c) Elasticsearch B.V (https://www.elastic.co)
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 * @license   https://www.gnu.org/licenses/lgpl-2.1.html GNU Lesser General Public License, Version 2.1
 *
 * Licensed to Elasticsearch B.V under one or more agreements.
 * Elasticsearch B.V licenses this file to you under the Apache 2.0 License or
 * the GNU Lesser General Public License, Version 2.1, at your option.
 * See the LICENSE file in the project root for more information.
 */
namespace Open_Search\Endpoints\Nodes;

use Open_Search\Endpoints\Abstract_Endpoint;
/**
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Info extends Abstract_Endpoint
{
    protected $node_id_or_metric;
    protected $metric;
    protected $node_id;
    public function get_uri(): string
    {
        $node_id_or_metric = $this->node_id_or_metric ? rawurlencode((string) $this->node_id_or_metric) : null;
        $metric = $this->metric ? rawurlencode((string) $this->metric) : null;
        $node_id = $this->node_id ? rawurlencode((string) $this->node_id) : null;
        if (isset($node_id_or_metric)) {
            return "/_nodes/{$node_id_or_metric}";
        }
        if (isset($node_id) && isset($metric)) {
            return "/_nodes/{$node_id}/{$metric}";
        }
        if (isset($node_id)) {
            return "/_nodes/{$node_id}";
        }
        if (isset($metric)) {
            return "/_nodes/{$metric}";
        }
        return '/_nodes';
    }
    public function get_param_whitelist(): array
    {
        return ['flat_settings', 'timeout', 'pretty', 'human', 'error_trace', 'source', 'filter_path'];
    }
    public function get_method(): string
    {
        return 'GET';
    }
    public function set_node_id_or_metric($node_id_or_metric): static
    {
        if (is_null($node_id_or_metric)) {
            return $this;
        }
        $this->node_id_or_metric = $node_id_or_metric;
        return $this;
    }
    public function set_metric($metric): static
    {
        if (!isset($metric)) {
            return $this;
        }
        if (is_array($metric) === true) {
            $metric = implode(',', $metric);
        }
        $this->metric = rawurlencode((string) $metric);
        return $this;
    }
    public function set_node_id($node_id): static
    {
        if (!isset($node_id)) {
            return $this;
        }
        if (is_array($node_id) === true) {
            $node_id = implode(',', $node_id);
        }
        $this->node_id = rawurlencode((string) $node_id);
        return $this;
    }
}