<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Namespaces;

use Open_Search\Endpoints\Asynchronous_Search\Delete;
use Open_Search\Endpoints\Asynchronous_Search\Get;
use Open_Search\Endpoints\Asynchronous_Search\Search;
use Open_Search\Endpoints\Asynchronous_Search\Stats;
/**
 * Class AsynchronousSearchNamespace
 *
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Asynchronous_Search_Namespace extends Abstract_Namespace
{
    /**
     * Deletes any responses from an asynchronous search.
     *
     * @param array{id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - id: (Required)
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        return $this->perform_request($endpoint);
    }
    /**
     * Gets partial responses from an asynchronous search.
     *
     * @param array{id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - id: (Required)
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $endpoint = $this->endpoint_factory->get_endpoint(Get::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        return $this->perform_request($endpoint);
    }
    /**
     * Performs an asynchronous search.
     *
     * @param array{index?: string, keep_alive?: string, keep_on_completion?: bool, wait_for_completion_timeout?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - index: The name of the index to be searched. Can be an individual name, a comma-separated list of indexes, or a wildcard expression of index names.
     * - keep_alive: The amount of time that the result is saved in the cluster. For example, `2d` means that the results are stored in the cluster for 48 hours. The saved search results are deleted after this period or if the search is canceled. Note that this includes the query execution time. If the query exceeds this amount of time, the process cancels this query automatically.
     * - keep_on_completion: Whether to save the results in the cluster after the search is complete. You can examine the stored results at a later time.
     * - wait_for_completion_timeout: The amount of time to wait for the results. You can poll the remaining results based on an ID. The maximum value is 300 seconds. Default is `1s`.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function search(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Search::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Monitors any asynchronous searches that are `running`, `completed`, or `persisted`.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function stats(array $params = [])
    {
        $endpoint = $this->endpoint_factory->get_endpoint(Stats::class);
        $endpoint->set_params($params);
        return $this->perform_request($endpoint);
    }
}