<?php

declare (strict_types=1);
/**
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * OpenSearch PHP client
 *
 * @link      https://github.com/opensearch-project/opensearch-php/
 * @copyright Copyright (c) Elasticsearch B.V (https://www.elastic.co)
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 * @license   https://www.gnu.org/licenses/lgpl-2.1.html GNU Lesser General Public License, Version 2.1
 *
 * Licensed to Elasticsearch B.V under one or more agreements.
 * Elasticsearch B.V licenses this file to you under the Apache 2.0 License or
 * the GNU Lesser General Public License, Version 2.1, at your option.
 * See the LICENSE file in the project root for more information.
 */
namespace Open_Search\Namespaces;

use Open_Search\Endpoints\Cluster\Allocation_Explain;
use Open_Search\Endpoints\Cluster\Delete_Component_Template;
use Open_Search\Endpoints\Cluster\Delete_Decommission_Awareness;
use Open_Search\Endpoints\Cluster\Delete_Voting_Config_Exclusions;
use Open_Search\Endpoints\Cluster\Delete_Weighted_Routing;
use Open_Search\Endpoints\Cluster\Exists_Component_Template;
use Open_Search\Endpoints\Cluster\Get_Component_Template;
use Open_Search\Endpoints\Cluster\Get_Decommission_Awareness;
use Open_Search\Endpoints\Cluster\Get_Settings;
use Open_Search\Endpoints\Cluster\Get_Weighted_Routing;
use Open_Search\Endpoints\Cluster\Health;
use Open_Search\Endpoints\Cluster\Pending_Tasks;
use Open_Search\Endpoints\Cluster\Post_Voting_Config_Exclusions;
use Open_Search\Endpoints\Cluster\Put_Component_Template;
use Open_Search\Endpoints\Cluster\Put_Decommission_Awareness;
use Open_Search\Endpoints\Cluster\Put_Settings;
use Open_Search\Endpoints\Cluster\Put_Weighted_Routing;
use Open_Search\Endpoints\Cluster\Remote_Info;
use Open_Search\Endpoints\Cluster\Reroute;
use Open_Search\Endpoints\Cluster\State;
use Open_Search\Endpoints\Cluster\Stats;
/**
 * Class ClusterNamespace
 *
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Cluster_Namespace extends Abstract_Namespace
{
    /**
     * Explains how shards are allocated in the current cluster and provides an explanation for why unassigned shards can't be allocated to a node.
     *
     * @param array{include_disk_info?: bool, include_yes_decisions?: bool, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - include_disk_info: When `true`, returns information about disk usage and shard sizes. (Default: false)
     * - include_yes_decisions: When `true`, returns any `YES` decisions in the allocation explanation. `YES` decisions indicate when a particular shard allocation attempt was successful for the given node. (Default: false)
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body: The index, shard, and primary flag for which to generate an explanation. Leave this empty to generate an explanation for the first unassigned shard.
     * @return array
     */
    public function allocation_explain(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Allocation_Explain::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Deletes a component template.
     *
     * @param array{name?: string, cluster_manager_timeout?: string, master_timeout?: string, timeout?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - name: The name of the component template to delete. Supports wildcard (*) expressions.
     * - cluster_manager_timeout: The amount of time to wait for a response from the cluster manager node. For more information about supported time units, see [Common parameters](https://opensearch.org/docs/latest/api-reference/common-parameters/#time-units).
     * - master_timeout:
     * - timeout:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete_component_template(array $params = [])
    {
        $name = $this->extract_argument($params, 'name');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Component_Template::class);
        $endpoint->set_params($params);
        $endpoint->set_name($name);
        return $this->perform_request($endpoint);
    }
    /**
     * Recommissions a decommissioned zone.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete_decommission_awareness(array $params = [])
    {
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Decommission_Awareness::class);
        $endpoint->set_params($params);
        return $this->perform_request($endpoint);
    }
    /**
     * Clears any cluster voting configuration exclusions.
     *
     * @param array{wait_for_removal?: bool, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - wait_for_removal: Specifies whether to wait for all excluded nodes to be removed from the cluster before clearing the voting configuration exclusions list. When `true`, all excluded nodes are removed from the cluster before this API takes any action. When `false`, the voting configuration exclusions list is cleared even if some excluded nodes are still in the cluster. (Default: true)
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete_voting_config_exclusions(array $params = [])
    {
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Voting_Config_Exclusions::class);
        $endpoint->set_params($params);
        return $this->perform_request($endpoint);
    }
    /**
     * Delete weighted shard routing weights.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function delete_weighted_routing(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Weighted_Routing::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Returns information about whether a particular component template exist.
     *
     * @param array{name?: string, cluster_manager_timeout?: string, local?: bool, master_timeout?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - name: The name of the component template. Wildcard (*) expressions are supported.
     * - cluster_manager_timeout: The amount of time to wait for a response from the cluster manager node. For more information about supported time units, see [Common parameters](https://opensearch.org/docs/latest/api-reference/common-parameters/#time-units).
     * - local: When `true`, the request retrieves information from the local node only. When `false`, information is retrieved from the cluster manager node. (Default: false)
     * - master_timeout:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     */
    public function exists_component_template(array $params = []): bool
    {
        $name = $this->extract_argument($params, 'name');
        // Legacy option to manually make this verbose so we can check status code.
        // @todo remove in 3.0.0
        $params['client']['verbose'] = true;
        $endpoint = $this->endpoint_factory->get_endpoint(Exists_Component_Template::class);
        $endpoint->set_params($params);
        $endpoint->set_name($name);
        return Boolean_Request_Wrapper::send_request($endpoint, $this->http_transport);
    }
    /**
     * Returns one or more component templates.
     *
     * @param array{name?: mixed, cluster_manager_timeout?: string, flat_settings?: bool, local?: bool, master_timeout?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - name: The name of the component template to retrieve. Wildcard (`*`) expressions are supported.
     * - cluster_manager_timeout: The amount of time to wait for a response from the cluster manager node. For more information about supported time units, see [Common parameters](https://opensearch.org/docs/latest/api-reference/common-parameters/#time-units).
     * - flat_settings: Whether to return settings in the flat form, which can improve readability, especially for heavily nested settings. For example, the flat form of `"cluster": { "max_shards_per_node": 500 }` is `"cluster.max_shards_per_node": "500"`. (Default: false)
     * - local: When `true`, the request retrieves information from the local node only. When `false`, information is retrieved from the cluster manager node. (Default: false)
     * - master_timeout:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_component_template(array $params = [])
    {
        $name = $this->extract_argument($params, 'name');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Component_Template::class);
        $endpoint->set_params($params);
        $endpoint->set_name($name);
        return $this->perform_request($endpoint);
    }
    /**
     * Retrieves the decommission status for all zones.
     *
     * @param array{awareness_attribute_name?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - awareness_attribute_name: The name of the awareness attribute.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_decommission_awareness(array $params = [])
    {
        $awareness_attribute_name = $this->extract_argument($params, 'awareness_attribute_name');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Decommission_Awareness::class);
        $endpoint->set_params($params);
        $endpoint->set_awareness_attribute_name($awareness_attribute_name);
        return $this->perform_request($endpoint);
    }
    /**
     * Returns cluster settings.
     *
     * @param array{cluster_manager_timeout?: string, flat_settings?: bool, include_defaults?: bool, master_timeout?: string, timeout?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - cluster_manager_timeout: The amount of time to wait for a response from the cluster manager node. For more information about supported time units, see [Common parameters](https://opensearch.org/docs/latest/api-reference/common-parameters/#time-units).
     * - flat_settings: Whether to return settings in the flat form, which can improve readability, especially for heavily nested settings. For example, the flat form of `"cluster": { "max_shards_per_node": 500 }` is `"cluster.max_shards_per_node": "500"`. (Default: false)
     * - include_defaults: When `true`, returns default cluster settings from the local node. (Default: false)
     * - master_timeout:
     * - timeout:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_settings(array $params = [])
    {
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Settings::class);
        $endpoint->set_params($params);
        return $this->perform_request($endpoint);
    }
    /**
     * Fetches weighted shard routing weights.
     *
     * @param array{attribute?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - attribute: The name of the awareness attribute.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_weighted_routing(array $params = [])
    {
        $attribute = $this->extract_argument($params, 'attribute');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Weighted_Routing::class);
        $endpoint->set_params($params);
        $endpoint->set_attribute($attribute);
        return $this->perform_request($endpoint);
    }
    /**
     * Returns basic information about the health of the cluster.
     *
     * @param array{index?: mixed, awareness_attribute?: string, cluster_manager_timeout?: string, expand_wildcards?: mixed, level?: mixed, local?: bool, master_timeout?: string, timeout?: string, wait_for_active_shards?: mixed, wait_for_events?: mixed, wait_for_no_initializing_shards?: bool, wait_for_no_relocating_shards?: bool, wait_for_nodes?: mixed, wait_for_status?: mixed, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - index:
     * - awareness_attribute: The name of the awareness attribute for which to return the cluster health status (for example, `zone`). Applicable only if `level` is set to `awareness_attributes`.
     * - cluster_manager_timeout: The amount of time to wait for a response from the cluster manager node. For more information about supported time units, see [Common parameters](https://opensearch.org/docs/latest/api-reference/common-parameters/#time-units).
     * - expand_wildcards:
     * - level: (Options: awareness_attributes, cluster, indices, shards)
     * - local: Whether to return information from the local node only instead of from the cluster manager node. (Default: false)
     * - master_timeout:
     * - timeout: The amount of time to wait for a response from the cluster manager node. For more information about supported time units, see [Common parameters](https://opensearch.org/docs/latest/api-reference/common-parameters/#time-units).
     * - wait_for_active_shards:
     * - wait_for_events:
     * - wait_for_no_initializing_shards: Whether to wait until there are no initializing shards in the cluster. (Default: false)
     * - wait_for_no_relocating_shards: Whether to wait until there are no relocating shards in the cluster. (Default: false)
     * - wait_for_nodes: Waits until the specified number of nodes (`N`) is available. Accepts `>=N`, `<=N`, `>N`, and `<N`. You can also use `ge(N)`, `le(N)`, `gt(N)`, and `lt(N)` notation.
     * - wait_for_status: Waits until the cluster health reaches the specified status or better.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function health(array $params = [])
    {
        $index = $this->extract_argument($params, 'index');
        $endpoint = $this->endpoint_factory->get_endpoint(Health::class);
        $endpoint->set_params($params);
        $endpoint->set_index($index);
        return $this->perform_request($endpoint);
    }
    /**
     * Returns a list of pending cluster-level tasks, such as index creation, mapping updates,or new allocations.
     *
     * @param array{cluster_manager_timeout?: string, local?: bool, master_timeout?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - cluster_manager_timeout: The amount of time to wait for a response from the cluster manager node. For more information about supported time units, see [Common parameters](https://opensearch.org/docs/latest/api-reference/common-parameters/#time-units).
     * - local: When `true`, the request retrieves information from the local node only. When `false`, information is retrieved from the cluster manager node. (Default: false)
     * - master_timeout:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function pending_tasks(array $params = [])
    {
        $endpoint = $this->endpoint_factory->get_endpoint(Pending_Tasks::class);
        $endpoint->set_params($params);
        return $this->perform_request($endpoint);
    }
    /**
     * Updates the cluster voting configuration by excluding certain node IDs or names.
     *
     * @param array{node_ids?: mixed, node_names?: mixed, timeout?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - node_ids: A comma-separated list of node IDs to exclude from the voting configuration. When using this setting, you cannot also specify `node_names`. Either `node_ids` or `node_names` are required to receive a valid response.
     * - node_names: A comma-separated list of node names to exclude from the voting configuration. When using this setting, you cannot also specify `node_ids`. Either `node_ids` or `node_names` are required to receive a valid response.
     * - timeout: When adding a voting configuration exclusion, the API waits for the specified nodes to be excluded from the voting configuration before returning a response. If the timeout expires before the appropriate condition is satisfied, the request fails and returns an error.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function post_voting_config_exclusions(array $params = [])
    {
        $endpoint = $this->endpoint_factory->get_endpoint(Post_Voting_Config_Exclusions::class);
        $endpoint->set_params($params);
        return $this->perform_request($endpoint);
    }
    /**
     * Creates or updates a component template.
     *
     * @param array{name?: string, cluster_manager_timeout?: string, create?: bool, master_timeout?: string, timeout?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - name: The name of the component template to create. OpenSearch includes the following built-in component templates: `logs-mappings`, `logs-settings`, `metrics-mappings`, `metrics-settings`, `synthetics-mapping`, and `synthetics-settings`. OpenSearch uses these templates to configure backing indexes for its data streams. If you want to overwrite one of these templates, set the replacement template `version` to a higher value than the current version. If you want to disable all built-in component and index templates, set `stack.templates.enabled` to `false` using the [Cluster Update Settings API](https://opensearch.org/docs/latest/api-reference/cluster-api/cluster-settings/).
     * - cluster_manager_timeout: The amount of time to wait for a response from the cluster manager node. For more information about supported time units, see [Common parameters](https://opensearch.org/docs/latest/api-reference/common-parameters/#time-units).
     * - create: When `true`, this request cannot replace or update existing component templates. (Default: false)
     * - master_timeout:
     * - timeout:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body: The template definition. (Required)
     * @return array
     */
    public function put_component_template(array $params = [])
    {
        $name = $this->extract_argument($params, 'name');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Put_Component_Template::class);
        $endpoint->set_params($params);
        $endpoint->set_name($name);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Decommissions a cluster zone based on awareness. This can greatly benefit multi-zone deployments, where awareness attributes can aid in applying new upgrades to a cluster in a controlled fashion.
     *
     * @param array{awareness_attribute_name?: string, awareness_attribute_value?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - awareness_attribute_name: The name of the awareness attribute.
     * - awareness_attribute_value: The value of the awareness attribute. For example, if you have shards allocated in two different zones, you can give each zone a value of `zone-a` or `zoneb`. The cluster decommission operation decommissions the zone listed in the method.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function put_decommission_awareness(array $params = [])
    {
        $awareness_attribute_name = $this->extract_argument($params, 'awareness_attribute_name');
        $awareness_attribute_value = $this->extract_argument($params, 'awareness_attribute_value');
        $endpoint = $this->endpoint_factory->get_endpoint(Put_Decommission_Awareness::class);
        $endpoint->set_params($params);
        $endpoint->set_awareness_attribute_name($awareness_attribute_name);
        $endpoint->set_awareness_attribute_value($awareness_attribute_value);
        return $this->perform_request($endpoint);
    }
    /**
     * Updates the cluster settings.
     *
     * @param array{cluster_manager_timeout?: string, flat_settings?: bool, master_timeout?: string, timeout?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - cluster_manager_timeout: The amount of time to wait for a response from the cluster manager node. For more information about supported time units, see [Common parameters](https://opensearch.org/docs/latest/api-reference/common-parameters/#time-units).
     * - flat_settings: Whether to return settings in the flat form, which can improve readability, especially for heavily nested settings. For example, the flat form of `"cluster": { "max_shards_per_node": 500 }` is `"cluster.max_shards_per_node": "500"`. (Default: false)
     * - master_timeout:
     * - timeout:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body: The cluster settings to update. (Required)
     * @return array
     */
    public function put_settings(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Put_Settings::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Updates weighted shard routing weights.
     *
     * @param array{attribute?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - attribute: The name of awareness attribute, usually `zone`.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function put_weighted_routing(array $params = [])
    {
        $attribute = $this->extract_argument($params, 'attribute');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Put_Weighted_Routing::class);
        $endpoint->set_params($params);
        $endpoint->set_attribute($attribute);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Returns the information about configured remote clusters.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function remote_info(array $params = [])
    {
        $endpoint = $this->endpoint_factory->get_endpoint(Remote_Info::class);
        $endpoint->set_params($params);
        return $this->perform_request($endpoint);
    }
    /**
     * Allows to manually change the allocation of individual shards in the cluster.
     *
     * @param array{cluster_manager_timeout?: string, dry_run?: bool, explain?: bool, master_timeout?: string, metric?: mixed, retry_failed?: bool, timeout?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - cluster_manager_timeout: The amount of time to wait for a response from the cluster manager node. For more information about supported time units, see [Common parameters](https://opensearch.org/docs/latest/api-reference/common-parameters/#time-units).
     * - dry_run: When `true`, the request simulates the operation and returns the resulting state.
     * - explain: When `true`, the response contains an explanation of why reroute certain commands can or cannot be executed.
     * - master_timeout:
     * - metric: Limits the information returned to the specified metrics.
     * - retry_failed: When `true`, retries shard allocation if it was blocked because of too many subsequent failures.
     * - timeout:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body: The definition of `commands` to perform (`move`, `cancel`, `allocate`)
     * @return array
     */
    public function reroute(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Reroute::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Returns comprehensive information about the state of the cluster.
     *
     * @param array{metric?: mixed, index?: mixed, allow_no_indices?: bool, cluster_manager_timeout?: string, expand_wildcards?: mixed, flat_settings?: bool, ignore_unavailable?: bool, local?: bool, master_timeout?: string, wait_for_metadata_version?: int, wait_for_timeout?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - metric: Limits the information returned to only the [specified metric groups](https://opensearch.org/docs/latest/api-reference/cluster-api/cluster-stats/#metric-groups).
     * - index:
     * - allow_no_indices: Whether to ignore a wildcard index expression that resolves into no concrete indexes. This includes the `_all` string or when no indexes have been specified.
     * - cluster_manager_timeout: The amount of time to wait for a response from the cluster manager node. For more information about supported time units, see [Common parameters](https://opensearch.org/docs/latest/api-reference/common-parameters/#time-units).
     * - expand_wildcards:
     * - flat_settings: Whether to return settings in the flat form, which can improve readability, especially for heavily nested settings. For example, the flat form of `"cluster": { "max_shards_per_node": 500 }` is `"cluster.max_shards_per_node": "500"`. (Default: false)
     * - ignore_unavailable: Whether the specified concrete indexes should be ignored when unavailable (missing or closed).
     * - local: Whether to return information from the local node only instead of from the cluster manager node. (Default: false)
     * - master_timeout:
     * - wait_for_metadata_version: Wait for the metadata version to be equal or greater than the specified metadata version.
     * - wait_for_timeout: The maximum time to wait for `wait_for_metadata_version` before timing out.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function state(array $params = [])
    {
        $metric = $this->extract_argument($params, 'metric');
        $index = $this->extract_argument($params, 'index');
        $endpoint = $this->endpoint_factory->get_endpoint(State::class);
        $endpoint->set_params($params);
        $endpoint->set_metric($metric);
        $endpoint->set_index($index);
        return $this->perform_request($endpoint);
    }
    /**
     * Returns a high-level overview of cluster statistics.
     *
     * @param array{index_metric?: mixed, metric?: mixed, node_id?: mixed, flat_settings?: bool, timeout?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - index_metric: A comma-separated list of [index metric groups](https://opensearch.org/docs/latest/api-reference/cluster-api/cluster-stats/#index-metric-groups), for example, `docs,store`.
     * - metric: Limit the information returned to the specified metrics.
     * - node_id:
     * - flat_settings: Whether to return settings in the flat form, which can improve readability, especially for heavily nested settings. For example, the flat form of `"cluster": { "max_shards_per_node": 500 }` is `"cluster.max_shards_per_node": "500"`. (Default: false)
     * - timeout: The amount of time to wait for each node to respond. If a node does not respond before its timeout expires, the response does not include its stats. However, timed out nodes are included in the response's `_nodes.failed` property. Defaults to no timeout.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function stats(array $params = [])
    {
        $index_metric = $this->extract_argument($params, 'index_metric');
        $metric = $this->extract_argument($params, 'metric');
        $node_id = $this->extract_argument($params, 'node_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Stats::class);
        $endpoint->set_params($params);
        $endpoint->set_index_metric($index_metric);
        $endpoint->set_metric($metric);
        $endpoint->set_node_id($node_id);
        return $this->perform_request($endpoint);
    }
}