<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Namespaces;

use Open_Search\Endpoints\Ingestion\Get_State;
use Open_Search\Endpoints\Ingestion\Pause;
use Open_Search\Endpoints\Ingestion\Resume;
/**
 * Class IngestionNamespace
 *
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Ingestion_Namespace extends Abstract_Namespace
{
    /**
     * Use this API to retrieve the ingestion state for a given index.
     *
     * @param array{index?: string, next_token?: string, size?: int, timeout?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - index: Index for which ingestion state should be retrieved.
     * - next_token: Token to retrieve the next page of results.
     * - size: Number of results to return per page.
     * - timeout: Timeout for the request.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_state(array $params = [])
    {
        $index = $this->extract_argument($params, 'index');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_State::class);
        $endpoint->set_params($params);
        $endpoint->set_index($index);
        return $this->perform_request($endpoint);
    }
    /**
     * Use this API to pause ingestion for a given index.
     *
     * @param array{index?: string, cluster_manager_timeout?: string, timeout?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - index: Index for which ingestion should be paused.
     * - cluster_manager_timeout: Time to wait for cluster manager connection.
     * - timeout: Timeout for the request.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function pause(array $params = [])
    {
        $index = $this->extract_argument($params, 'index');
        $endpoint = $this->endpoint_factory->get_endpoint(Pause::class);
        $endpoint->set_params($params);
        $endpoint->set_index($index);
        return $this->perform_request($endpoint);
    }
    /**
     * Use this API to resume ingestion for the given index.
     *
     * @param array{index?: string, cluster_manager_timeout?: string, timeout?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - index: Index for which ingestion should be resumed.
     * - cluster_manager_timeout: Time to wait for cluster manager connection.
     * - timeout: Timeout for the request.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function resume(array $params = [])
    {
        $index = $this->extract_argument($params, 'index');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Resume::class);
        $endpoint->set_params($params);
        $endpoint->set_index($index);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
}