<?php

declare (strict_types=1);
/**
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * OpenSearch PHP client
 *
 * @link      https://github.com/opensearch-project/opensearch-php/
 * @copyright Copyright (c) Elasticsearch B.V (https://www.elastic.co)
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 * @license   https://www.gnu.org/licenses/lgpl-2.1.html GNU Lesser General Public License, Version 2.1
 *
 * Licensed to Elasticsearch B.V under one or more agreements.
 * Elasticsearch B.V licenses this file to you under the Apache 2.0 License or
 * the GNU Lesser General Public License, Version 2.1, at your option.
 * See the LICENSE file in the project root for more information.
 */
namespace Open_Search\Namespaces;

use Open_Search\Endpoints\Ingest\Delete_Pipeline;
use Open_Search\Endpoints\Ingest\Get_Pipeline;
use Open_Search\Endpoints\Ingest\Processor_Grok;
use Open_Search\Endpoints\Ingest\Put_Pipeline;
use Open_Search\Endpoints\Ingest\Simulate;
/**
 * Class IngestNamespace
 *
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Ingest_Namespace extends Abstract_Namespace
{
    /**
     * Deletes an ingest pipeline.
     *
     * @param array{id?: string, cluster_manager_timeout?: string, master_timeout?: string, timeout?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - id: The pipeline ID or wildcard expression of pipeline IDs used to limit the request. To delete all ingest pipelines in a cluster, use a value of `*`. (Required)
     * - cluster_manager_timeout: The amount of time allowed to establish a connection to the cluster manager node.
     * - master_timeout: Period to wait for a connection to the cluster-manager node. If no response is received before the timeout expires, the request fails and returns an error.
     * - timeout: The amount of time to wait for a response.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete_pipeline(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Pipeline::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        return $this->perform_request($endpoint);
    }
    /**
     * Returns an ingest pipeline.
     *
     * @param array{id?: string, cluster_manager_timeout?: string, master_timeout?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - id: A comma-separated list of pipeline IDs to retrieve. Wildcard (`*`) expressions are supported. To get all ingest pipelines, omit this parameter or use `*`. (Required)
     * - cluster_manager_timeout: The amount of time allowed to establish a connection to the cluster manager node.
     * - master_timeout: Period to wait for a connection to the cluster-manager node. If no response is received before the timeout expires, the request fails and returns an error.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_pipeline(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Pipeline::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        return $this->perform_request($endpoint);
    }
    /**
     * Returns a list of built-in grok patterns.
     *
     * @param array{s?: bool, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - s: Determines how to sort returned grok patterns by key name. (Default: false)
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function processor_grok(array $params = [])
    {
        $endpoint = $this->endpoint_factory->get_endpoint(Processor_Grok::class);
        $endpoint->set_params($params);
        return $this->perform_request($endpoint);
    }
    /**
     * Creates or updates an ingest pipeline.
     *
     * @param array{id?: string, cluster_manager_timeout?: string, master_timeout?: string, timeout?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - id: The ID of the ingest pipeline. (Required)
     * - cluster_manager_timeout: The amount of time allowed to establish a connection to the cluster manager node.
     * - master_timeout: Period to wait for a connection to the cluster-manager node. If no response is received before the timeout expires, the request fails and returns an error.
     * - timeout: The amount of time to wait for a response.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body: The ingest definition. (Required)
     * @return array
     */
    public function put_pipeline(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Put_Pipeline::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Simulates an ingest pipeline with example documents.
     *
     * @param array{id?: string, verbose?: bool, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - id: The pipeline to test. If you don't specify a `pipeline` in the request body, this parameter is required. (Required)
     * - verbose: When `true`, the response includes output data for each processor in the pipeline (Default: false)
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body: The simulate definition (Required)
     * @return array
     */
    public function simulate(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Simulate::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
}