<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Namespaces;

use Open_Search\Endpoints\Ism\Add_Policy;
use Open_Search\Endpoints\Ism\Change_Policy;
use Open_Search\Endpoints\Ism\Delete_Policy;
use Open_Search\Endpoints\Ism\Exists_Policy;
use Open_Search\Endpoints\Ism\Explain_Policy;
use Open_Search\Endpoints\Ism\Get_Policies;
use Open_Search\Endpoints\Ism\Get_Policy;
use Open_Search\Endpoints\Ism\Put_Policies;
use Open_Search\Endpoints\Ism\Put_Policy;
use Open_Search\Endpoints\Ism\Refresh_Search_Analyzers;
use Open_Search\Endpoints\Ism\Remove_Policy;
use Open_Search\Endpoints\Ism\Retry_Index;
/**
 * Class IsmNamespace
 *
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Ism_Namespace extends Abstract_Namespace
{
    /**
     * Adds a policy to an index.
     *
     * @param array{index?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - index:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function add_policy(array $params = [])
    {
        $index = $this->extract_argument($params, 'index');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Add_Policy::class);
        $endpoint->set_params($params);
        $endpoint->set_index($index);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Updates the managed index policy to a new policy.
     *
     * @param array{index?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - index:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function change_policy(array $params = [])
    {
        $index = $this->extract_argument($params, 'index');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Change_Policy::class);
        $endpoint->set_params($params);
        $endpoint->set_index($index);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Deletes a policy.
     *
     * @param array{policy_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - policy_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete_policy(array $params = [])
    {
        $policy_id = $this->extract_argument($params, 'policy_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Policy::class);
        $endpoint->set_params($params);
        $endpoint->set_policy_id($policy_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Checks for the existence of a policy.
     *
     * @param array{policy_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - policy_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     */
    public function exists_policy(array $params = []): bool
    {
        $policy_id = $this->extract_argument($params, 'policy_id');
        // Legacy option to manually make this verbose so we can check status code.
        // @todo remove in 3.0.0
        $params['client']['verbose'] = true;
        $endpoint = $this->endpoint_factory->get_endpoint(Exists_Policy::class);
        $endpoint->set_params($params);
        $endpoint->set_policy_id($policy_id);
        return Boolean_Request_Wrapper::send_request($endpoint, $this->http_transport);
    }
    /**
     * Retrieves the currently applied policy on the specified indexes.
     *
     * @param array{index?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - index:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function explain_policy(array $params = [])
    {
        $index = $this->extract_argument($params, 'index');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Explain_Policy::class);
        $endpoint->set_params($params);
        $endpoint->set_index($index);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Retrieves the policies.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_policies(array $params = [])
    {
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Policies::class);
        $endpoint->set_params($params);
        return $this->perform_request($endpoint);
    }
    /**
     * Retrieves a specific policy.
     *
     * @param array{policy_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - policy_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_policy(array $params = [])
    {
        $policy_id = $this->extract_argument($params, 'policy_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Policy::class);
        $endpoint->set_params($params);
        $endpoint->set_policy_id($policy_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Creates or updates policies.
     *
     * @param array{if_primary_term?: int|float, if_seq_no?: int, policyID?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - if_primary_term: Only perform the operation if the document has this primary term.
     * - if_seq_no: Only perform the operation if the document has this sequence number.
     * - policyID:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function put_policies(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Put_Policies::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Creates or updates a policy.
     *
     * @param array{policy_id?: string, if_primary_term?: int|float, if_seq_no?: int, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - policy_id:
     * - if_primary_term: Only perform the operation if the document has this primary term.
     * - if_seq_no: Only perform the operation if the document has this sequence number.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function put_policy(array $params = [])
    {
        $policy_id = $this->extract_argument($params, 'policy_id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Put_Policy::class);
        $endpoint->set_params($params);
        $endpoint->set_policy_id($policy_id);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Refreshes search analyzers in real time.
     *
     * @param array{index?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - index:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function refresh_search_analyzers(array $params = [])
    {
        $index = $this->extract_argument($params, 'index');
        $endpoint = $this->endpoint_factory->get_endpoint(Refresh_Search_Analyzers::class);
        $endpoint->set_params($params);
        $endpoint->set_index($index);
        return $this->perform_request($endpoint);
    }
    /**
     * Removes a policy from an index.
     *
     * @param array{index?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - index:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function remove_policy(array $params = [])
    {
        $index = $this->extract_argument($params, 'index');
        $endpoint = $this->endpoint_factory->get_endpoint(Remove_Policy::class);
        $endpoint->set_params($params);
        $endpoint->set_index($index);
        return $this->perform_request($endpoint);
    }
    /**
     * Retries the failed action for an index.
     *
     * @param array{index?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - index:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function retry_index(array $params = [])
    {
        $index = $this->extract_argument($params, 'index');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Retry_Index::class);
        $endpoint->set_params($params);
        $endpoint->set_index($index);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
}