<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Namespaces;

use Open_Search\Endpoints\Ltr\Add_Features_To_Set;
use Open_Search\Endpoints\Ltr\Add_Features_To_Set_By_Query;
use Open_Search\Endpoints\Ltr\Cache_Stats;
use Open_Search\Endpoints\Ltr\Clear_Cache;
use Open_Search\Endpoints\Ltr\Create_Default_Store;
use Open_Search\Endpoints\Ltr\Create_Feature;
use Open_Search\Endpoints\Ltr\Create_Featureset;
use Open_Search\Endpoints\Ltr\Create_Model;
use Open_Search\Endpoints\Ltr\Create_Model_From_Set;
use Open_Search\Endpoints\Ltr\Create_Store;
use Open_Search\Endpoints\Ltr\Delete_Default_Store;
use Open_Search\Endpoints\Ltr\Delete_Feature;
use Open_Search\Endpoints\Ltr\Delete_Featureset;
use Open_Search\Endpoints\Ltr\Delete_Model;
use Open_Search\Endpoints\Ltr\Delete_Store;
use Open_Search\Endpoints\Ltr\Get_Feature;
use Open_Search\Endpoints\Ltr\Get_Featureset;
use Open_Search\Endpoints\Ltr\Get_Model;
use Open_Search\Endpoints\Ltr\Get_Store;
use Open_Search\Endpoints\Ltr\List_Stores;
use Open_Search\Endpoints\Ltr\Search_Features;
use Open_Search\Endpoints\Ltr\Search_Featuresets;
use Open_Search\Endpoints\Ltr\Search_Models;
use Open_Search\Endpoints\Ltr\Stats;
use Open_Search\Endpoints\Ltr\Update_Feature;
use Open_Search\Endpoints\Ltr\Update_Featureset;
/**
 * Class LtrNamespace
 *
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Ltr_Namespace extends Abstract_Namespace
{
    /**
     * Add features to an existing feature set in the default feature store.
     *
     * @param array{name?: string, store?: string, merge?: bool, routing?: string, version?: int, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - name: The name of the feature set to add features to.
     * - store: The name of the feature store.
     * - merge: Whether to merge the feature list or append only. (Default: false)
     * - routing: Specific routing value.
     * - version: Version check to ensure feature set is modified with expected version.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body: (Required)
     * @return array
     */
    public function add_features_to_set(array $params = [])
    {
        $name = $this->extract_argument($params, 'name');
        $store = $this->extract_argument($params, 'store');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Add_Features_To_Set::class);
        $endpoint->set_params($params);
        $endpoint->set_name($name);
        $endpoint->set_store($store);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Add features to an existing feature set in the default feature store.
     *
     * @param array{name?: string, query?: string, store?: string, merge?: bool, routing?: string, version?: int, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - name: The name of the feature set to add features to.
     * - query: Query string to filter existing features from the store by name. When provided, only features matching this query will be added to the feature set, and no request body should be included.
     * - store: The name of the feature store.
     * - merge: Whether to merge the feature list or append only. (Default: false)
     * - routing: Specific routing value.
     * - version: Version check to ensure feature set is modified with expected version.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function add_features_to_set_by_query(array $params = [])
    {
        $name = $this->extract_argument($params, 'name');
        $query = $this->extract_argument($params, 'query');
        $store = $this->extract_argument($params, 'store');
        $endpoint = $this->endpoint_factory->get_endpoint(Add_Features_To_Set_By_Query::class);
        $endpoint->set_params($params);
        $endpoint->set_name($name);
        $endpoint->set_query($query);
        $endpoint->set_store($store);
        return $this->perform_request($endpoint);
    }
    /**
     * Retrieves cache statistics for all feature stores.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function cache_stats(array $params = [])
    {
        $endpoint = $this->endpoint_factory->get_endpoint(Cache_Stats::class);
        $endpoint->set_params($params);
        return $this->perform_request($endpoint);
    }
    /**
     * Clears the store caches.
     *
     * @param array{store?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - store: The name of the feature store for which to clear the cache.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function clear_cache(array $params = [])
    {
        $store = $this->extract_argument($params, 'store');
        $endpoint = $this->endpoint_factory->get_endpoint(Clear_Cache::class);
        $endpoint->set_params($params);
        $endpoint->set_store($store);
        return $this->perform_request($endpoint);
    }
    /**
     * Creates the default feature store.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function create_default_store(array $params = [])
    {
        $endpoint = $this->endpoint_factory->get_endpoint(Create_Default_Store::class);
        $endpoint->set_params($params);
        return $this->perform_request($endpoint);
    }
    /**
     * Create or update a feature in the default feature store.
     *
     * @param array{id?: string, store?: string, routing?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - id: The name of the feature. (Required)
     * - store: The name of the feature store.
     * - routing: Specific routing value.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body: (Required)
     * @return array
     */
    public function create_feature(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $store = $this->extract_argument($params, 'store');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Create_Feature::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        $endpoint->set_store($store);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Create or update a feature set in the default feature store.
     *
     * @param array{id?: string, store?: string, routing?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - id: The name of the feature set. (Required)
     * - store: The name of the feature store.
     * - routing: Specific routing value.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body: (Required)
     * @return array
     */
    public function create_featureset(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $store = $this->extract_argument($params, 'store');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Create_Featureset::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        $endpoint->set_store($store);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Create or update a model in the default feature store.
     *
     * @param array{id?: string, store?: string, routing?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - id: The name of the model. (Required)
     * - store: The name of the feature store.
     * - routing: Specific routing value.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body: (Required)
     * @return array
     */
    public function create_model(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $store = $this->extract_argument($params, 'store');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Create_Model::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        $endpoint->set_store($store);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Create a model from an existing feature set in the default feature store.
     *
     * @param array{name?: string, store?: string, routing?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - name: The name of the feature set to use for creating the model.
     * - store: The name of the feature store.
     * - routing: Specific routing value.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body: (Required)
     * @return array
     */
    public function create_model_from_set(array $params = [])
    {
        $name = $this->extract_argument($params, 'name');
        $store = $this->extract_argument($params, 'store');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Create_Model_From_Set::class);
        $endpoint->set_params($params);
        $endpoint->set_name($name);
        $endpoint->set_store($store);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Creates a new feature store with the specified name.
     *
     * @param array{store?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - store: The name of the feature store.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function create_store(array $params = [])
    {
        $store = $this->extract_argument($params, 'store');
        $endpoint = $this->endpoint_factory->get_endpoint(Create_Store::class);
        $endpoint->set_params($params);
        $endpoint->set_store($store);
        return $this->perform_request($endpoint);
    }
    /**
     * Deletes the default feature store.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete_default_store(array $params = [])
    {
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Default_Store::class);
        $endpoint->set_params($params);
        return $this->perform_request($endpoint);
    }
    /**
     * Delete a feature from the default feature store.
     *
     * @param array{id?: string, store?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - id: The name of the feature. (Required)
     * - store: The name of the feature store.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete_feature(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $store = $this->extract_argument($params, 'store');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Feature::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        $endpoint->set_store($store);
        return $this->perform_request($endpoint);
    }
    /**
     * Delete a feature set from the default feature store.
     *
     * @param array{id?: string, store?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - id: The name of the feature set. (Required)
     * - store: The name of the feature store.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete_featureset(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $store = $this->extract_argument($params, 'store');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Featureset::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        $endpoint->set_store($store);
        return $this->perform_request($endpoint);
    }
    /**
     * Delete a model from the default feature store.
     *
     * @param array{id?: string, store?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - id: The name of the model. (Required)
     * - store: The name of the feature store.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete_model(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $store = $this->extract_argument($params, 'store');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Model::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        $endpoint->set_store($store);
        return $this->perform_request($endpoint);
    }
    /**
     * Deletes a feature store with the specified name.
     *
     * @param array{store?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - store: The name of the feature store.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete_store(array $params = [])
    {
        $store = $this->extract_argument($params, 'store');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Store::class);
        $endpoint->set_params($params);
        $endpoint->set_store($store);
        return $this->perform_request($endpoint);
    }
    /**
     * Get a feature from the default feature store.
     *
     * @param array{id?: string, store?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - id: The name of the feature. (Required)
     * - store: The name of the feature store.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_feature(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $store = $this->extract_argument($params, 'store');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Feature::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        $endpoint->set_store($store);
        return $this->perform_request($endpoint);
    }
    /**
     * Get a feature set from the default feature store.
     *
     * @param array{id?: string, store?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - id: The name of the feature set. (Required)
     * - store: The name of the feature store.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_featureset(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $store = $this->extract_argument($params, 'store');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Featureset::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        $endpoint->set_store($store);
        return $this->perform_request($endpoint);
    }
    /**
     * Get a model from the default feature store.
     *
     * @param array{id?: string, store?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - id: The name of the model. (Required)
     * - store: The name of the feature store.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_model(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $store = $this->extract_argument($params, 'store');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Model::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        $endpoint->set_store($store);
        return $this->perform_request($endpoint);
    }
    /**
     * Checks if a store exists.
     *
     * @param array{store?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - store: The name of the feature store.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_store(array $params = [])
    {
        $store = $this->extract_argument($params, 'store');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Store::class);
        $endpoint->set_params($params);
        $endpoint->set_store($store);
        return $this->perform_request($endpoint);
    }
    /**
     * Lists all available feature stores.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function list_stores(array $params = [])
    {
        $endpoint = $this->endpoint_factory->get_endpoint(List_Stores::class);
        $endpoint->set_params($params);
        return $this->perform_request($endpoint);
    }
    /**
     * Search for features in a feature store.
     *
     * @param array{store?: string, from?: int, prefix?: string, size?: int, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - store: The name of the feature store.
     * - from: The offset from the first result (for pagination). (Default: 0)
     * - prefix: A name prefix to filter features by.
     * - size: The number of features to return. (Default: 20)
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function search_features(array $params = [])
    {
        $store = $this->extract_argument($params, 'store');
        $endpoint = $this->endpoint_factory->get_endpoint(Search_Features::class);
        $endpoint->set_params($params);
        $endpoint->set_store($store);
        return $this->perform_request($endpoint);
    }
    /**
     * Search for feature sets in a feature store.
     *
     * @param array{store?: string, from?: int, prefix?: string, size?: int, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - store: The name of the feature store.
     * - from: The offset from the first result (for pagination). (Default: 0)
     * - prefix: A name prefix to filter feature sets by.
     * - size: The number of feature sets to return. (Default: 20)
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function search_featuresets(array $params = [])
    {
        $store = $this->extract_argument($params, 'store');
        $endpoint = $this->endpoint_factory->get_endpoint(Search_Featuresets::class);
        $endpoint->set_params($params);
        $endpoint->set_store($store);
        return $this->perform_request($endpoint);
    }
    /**
     * Search for models in a feature store.
     *
     * @param array{store?: string, from?: int, prefix?: string, size?: int, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - store: The name of the feature store.
     * - from: The offset from the first result (for pagination). (Default: 0)
     * - prefix: A name prefix to filter models by.
     * - size: The number of models to return. (Default: 20)
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function search_models(array $params = [])
    {
        $store = $this->extract_argument($params, 'store');
        $endpoint = $this->endpoint_factory->get_endpoint(Search_Models::class);
        $endpoint->set_params($params);
        $endpoint->set_store($store);
        return $this->perform_request($endpoint);
    }
    /**
     * Provides information about the current status of the LTR plugin.
     *
     * @param array{node_id?: mixed, stat?: mixed, timeout?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - node_id: A comma-separated list of node IDs or names to limit the returned information; use `_local` to return information from the node you're connecting to, leave empty to get information from all nodes.
     * - stat: A comma-separated list of stats to retrieve; use `_all` or empty string to retrieve all stats.
     * - timeout: The time in milliseconds to wait for a response.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function stats(array $params = [])
    {
        $node_id = $this->extract_argument($params, 'node_id');
        $stat = $this->extract_argument($params, 'stat');
        $endpoint = $this->endpoint_factory->get_endpoint(Stats::class);
        $endpoint->set_params($params);
        $endpoint->set_node_id($node_id);
        $endpoint->set_stat($stat);
        return $this->perform_request($endpoint);
    }
    /**
     * Update a feature in the default feature store.
     *
     * @param array{id?: string, store?: string, routing?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - id: The name of the feature. (Required)
     * - store: The name of the feature store.
     * - routing: Specific routing value.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body: (Required)
     * @return array
     */
    public function update_feature(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $store = $this->extract_argument($params, 'store');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Update_Feature::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        $endpoint->set_store($store);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Update a feature set in the default feature store.
     *
     * @param array{id?: string, store?: string, routing?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - id: The name of the feature set. (Required)
     * - store: The name of the feature store.
     * - routing: Specific routing value.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body: (Required)
     * @return array
     */
    public function update_featureset(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $store = $this->extract_argument($params, 'store');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Update_Featureset::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        $endpoint->set_store($store);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
}