<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Namespaces;

use Open_Search\Endpoints\Ml\Add_Agentic_Memory;
use Open_Search\Endpoints\Ml\Chunk_Model;
use Open_Search\Endpoints\Ml\Create_Connector;
use Open_Search\Endpoints\Ml\Create_Controller;
use Open_Search\Endpoints\Ml\Create_Memory;
use Open_Search\Endpoints\Ml\Create_Memory_Container;
use Open_Search\Endpoints\Ml\Create_Memory_Container_Session;
use Open_Search\Endpoints\Ml\Create_Message;
use Open_Search\Endpoints\Ml\Create_Model_Meta;
use Open_Search\Endpoints\Ml\Delete_Agent;
use Open_Search\Endpoints\Ml\Delete_Agentic_Memory;
use Open_Search\Endpoints\Ml\Delete_Agentic_Memory_Query;
use Open_Search\Endpoints\Ml\Delete_Connector;
use Open_Search\Endpoints\Ml\Delete_Controller;
use Open_Search\Endpoints\Ml\Delete_Memory;
use Open_Search\Endpoints\Ml\Delete_Memory_Container;
use Open_Search\Endpoints\Ml\Delete_Model;
use Open_Search\Endpoints\Ml\Delete_Model_Group;
use Open_Search\Endpoints\Ml\Delete_Task;
use Open_Search\Endpoints\Ml\Deploy_Model;
use Open_Search\Endpoints\Ml\Execute_Agent;
use Open_Search\Endpoints\Ml\Execute_Agent_Stream;
use Open_Search\Endpoints\Ml\Execute_Algorithm;
use Open_Search\Endpoints\Ml\Execute_Tool;
use Open_Search\Endpoints\Ml\Get_Agent;
use Open_Search\Endpoints\Ml\Get_Agentic_Memory;
use Open_Search\Endpoints\Ml\Get_All_Memories;
use Open_Search\Endpoints\Ml\Get_All_Messages;
use Open_Search\Endpoints\Ml\Get_All_Tools;
use Open_Search\Endpoints\Ml\Get_Connector;
use Open_Search\Endpoints\Ml\Get_Connectors;
use Open_Search\Endpoints\Ml\Get_Controller;
use Open_Search\Endpoints\Ml\Get_Memory;
use Open_Search\Endpoints\Ml\Get_Memory_Container;
use Open_Search\Endpoints\Ml\Get_Message;
use Open_Search\Endpoints\Ml\Get_Message_Traces;
use Open_Search\Endpoints\Ml\Get_Model;
use Open_Search\Endpoints\Ml\Get_Model_Group;
use Open_Search\Endpoints\Ml\Get_Model_Groups;
use Open_Search\Endpoints\Ml\Get_Profile;
use Open_Search\Endpoints\Ml\Get_Profile_Models;
use Open_Search\Endpoints\Ml\Get_Profile_Tasks;
use Open_Search\Endpoints\Ml\Get_Stats;
use Open_Search\Endpoints\Ml\Get_Task;
use Open_Search\Endpoints\Ml\Get_Tool;
use Open_Search\Endpoints\Ml\Load_Model;
use Open_Search\Endpoints\Ml\Predict;
use Open_Search\Endpoints\Ml\Predict_Model;
use Open_Search\Endpoints\Ml\Predict_Model_Stream;
use Open_Search\Endpoints\Ml\Register_Agents;
use Open_Search\Endpoints\Ml\Register_Model;
use Open_Search\Endpoints\Ml\Register_Model_Group;
use Open_Search\Endpoints\Ml\Register_Model_Meta;
use Open_Search\Endpoints\Ml\Search_Agentic_Memory;
use Open_Search\Endpoints\Ml\Search_Agents;
use Open_Search\Endpoints\Ml\Search_Connectors;
use Open_Search\Endpoints\Ml\Search_Memory;
use Open_Search\Endpoints\Ml\Search_Memory_Container;
use Open_Search\Endpoints\Ml\Search_Message;
use Open_Search\Endpoints\Ml\Search_Model_Group;
use Open_Search\Endpoints\Ml\Search_Models;
use Open_Search\Endpoints\Ml\Search_Tasks;
use Open_Search\Endpoints\Ml\Train;
use Open_Search\Endpoints\Ml\Train_Predict;
use Open_Search\Endpoints\Ml\Undeploy_Model;
use Open_Search\Endpoints\Ml\Unload_Model;
use Open_Search\Endpoints\Ml\Update_Agentic_Memory;
use Open_Search\Endpoints\Ml\Update_Connector;
use Open_Search\Endpoints\Ml\Update_Controller;
use Open_Search\Endpoints\Ml\Update_Memory;
use Open_Search\Endpoints\Ml\Update_Memory_Container;
use Open_Search\Endpoints\Ml\Update_Message;
use Open_Search\Endpoints\Ml\Update_Model;
use Open_Search\Endpoints\Ml\Update_Model_Group;
use Open_Search\Endpoints\Ml\Upload_Chunk;
use Open_Search\Endpoints\Ml\Upload_Model;
/**
 * Class MlNamespace
 *
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Ml_Namespace extends Abstract_Namespace
{
    /**
     * Add agentic memory to a memory container.
     *
     * @param array{memory_container_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - memory_container_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function add_agentic_memory(array $params = [])
    {
        $memory_container_id = $this->extract_argument($params, 'memory_container_id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Add_Agentic_Memory::class);
        $endpoint->set_params($params);
        $endpoint->set_memory_container_id($memory_container_id);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Uploads model chunk.
     *
     * @param array{chunk_number?: int, model_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - chunk_number:
     * - model_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function chunk_model(array $params = [])
    {
        $chunk_number = $this->extract_argument($params, 'chunk_number');
        $model_id = $this->extract_argument($params, 'model_id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Chunk_Model::class);
        $endpoint->set_params($params);
        $endpoint->set_chunk_number($chunk_number);
        $endpoint->set_model_id($model_id);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Creates a controller.
     *
     * @param array{model_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - model_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function create_controller(array $params = [])
    {
        $model_id = $this->extract_argument($params, 'model_id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Create_Controller::class);
        $endpoint->set_params($params);
        $endpoint->set_model_id($model_id);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Create a memory.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function create_memory(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Create_Memory::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Create a memory container.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function create_memory_container(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Create_Memory_Container::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Create session in a memory container.
     *
     * @param array{memory_container_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - memory_container_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function create_memory_container_session(array $params = [])
    {
        $memory_container_id = $this->extract_argument($params, 'memory_container_id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Create_Memory_Container_Session::class);
        $endpoint->set_params($params);
        $endpoint->set_memory_container_id($memory_container_id);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Create a message.
     *
     * @param array{memory_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - memory_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function create_message(array $params = [])
    {
        $memory_id = $this->extract_argument($params, 'memory_id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Create_Message::class);
        $endpoint->set_params($params);
        $endpoint->set_memory_id($memory_id);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Registers model metadata.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function create_model_meta(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Create_Model_Meta::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Delete an agent.
     *
     * @param array{agent_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - agent_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete_agent(array $params = [])
    {
        $agent_id = $this->extract_argument($params, 'agent_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Agent::class);
        $endpoint->set_params($params);
        $endpoint->set_agent_id($agent_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Delete a specific memory by its type and ID.
     *
     * @param array{id?: string, memory_container_id?: string, type?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - id: (Required)
     * - memory_container_id:
     * - type:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete_agentic_memory(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $memory_container_id = $this->extract_argument($params, 'memory_container_id');
        $type = $this->extract_argument($params, 'type');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Agentic_Memory::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        $endpoint->set_memory_container_id($memory_container_id);
        $endpoint->set_type($type);
        return $this->perform_request($endpoint);
    }
    /**
     * Delete multiple memories using a query to match specific criteria.
     *
     * @param array{memory_container_id?: string, type?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - memory_container_id:
     * - type:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function delete_agentic_memory_query(array $params = [])
    {
        $memory_container_id = $this->extract_argument($params, 'memory_container_id');
        $type = $this->extract_argument($params, 'type');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Agentic_Memory_Query::class);
        $endpoint->set_params($params);
        $endpoint->set_memory_container_id($memory_container_id);
        $endpoint->set_type($type);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Deletes a controller.
     *
     * @param array{model_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - model_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete_controller(array $params = [])
    {
        $model_id = $this->extract_argument($params, 'model_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Controller::class);
        $endpoint->set_params($params);
        $endpoint->set_model_id($model_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Delete a memory.
     *
     * @param array{memory_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - memory_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete_memory(array $params = [])
    {
        $memory_id = $this->extract_argument($params, 'memory_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Memory::class);
        $endpoint->set_params($params);
        $endpoint->set_memory_id($memory_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Delete a memory container.
     *
     * @param array{memory_container_id?: string, delete_all_memories?: bool, delete_memories?: mixed, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - memory_container_id:
     * - delete_all_memories: (Default: false)
     * - delete_memories:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete_memory_container(array $params = [])
    {
        $memory_container_id = $this->extract_argument($params, 'memory_container_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Memory_Container::class);
        $endpoint->set_params($params);
        $endpoint->set_memory_container_id($memory_container_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Deletes a model.
     *
     * @param array{id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - id: (Required)
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete_model(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Model::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        return $this->perform_request($endpoint);
    }
    /**
     * Deletes a model group.
     *
     * @param array{id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - id: (Required)
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete_model_group(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Model_Group::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        return $this->perform_request($endpoint);
    }
    /**
     * Deletes a task.
     *
     * @param array{task_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - task_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete_task(array $params = [])
    {
        $task_id = $this->extract_argument($params, 'task_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Task::class);
        $endpoint->set_params($params);
        $endpoint->set_task_id($task_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Execute an agent.
     *
     * @param array{agent_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - agent_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function execute_agent(array $params = [])
    {
        $agent_id = $this->extract_argument($params, 'agent_id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Execute_Agent::class);
        $endpoint->set_params($params);
        $endpoint->set_agent_id($agent_id);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Execute an agent in streaming mode.
     *
     * @param array{agent_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - agent_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function execute_agent_stream(array $params = [])
    {
        $agent_id = $this->extract_argument($params, 'agent_id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Execute_Agent_Stream::class);
        $endpoint->set_params($params);
        $endpoint->set_agent_id($agent_id);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Execute an algorithm.
     *
     * @param array{algorithm_name?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - algorithm_name:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function execute_algorithm(array $params = [])
    {
        $algorithm_name = $this->extract_argument($params, 'algorithm_name');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Execute_Algorithm::class);
        $endpoint->set_params($params);
        $endpoint->set_algorithm_name($algorithm_name);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Execute a tool.
     *
     * @param array{tool_name?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - tool_name:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function execute_tool(array $params = [])
    {
        $tool_name = $this->extract_argument($params, 'tool_name');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Execute_Tool::class);
        $endpoint->set_params($params);
        $endpoint->set_tool_name($tool_name);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Get an agent.
     *
     * @param array{agent_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - agent_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_agent(array $params = [])
    {
        $agent_id = $this->extract_argument($params, 'agent_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Agent::class);
        $endpoint->set_params($params);
        $endpoint->set_agent_id($agent_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Get a specific memory by its type and ID.
     *
     * @param array{id?: string, memory_container_id?: string, type?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - id: (Required)
     * - memory_container_id:
     * - type:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_agentic_memory(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $memory_container_id = $this->extract_argument($params, 'memory_container_id');
        $type = $this->extract_argument($params, 'type');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Agentic_Memory::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        $endpoint->set_memory_container_id($memory_container_id);
        $endpoint->set_type($type);
        return $this->perform_request($endpoint);
    }
    /**
     * Get all memories.
     *
     * @param array{max_results?: int, next_token?: int, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - max_results:
     * - next_token:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_all_memories(array $params = [])
    {
        $endpoint = $this->endpoint_factory->get_endpoint(Get_All_Memories::class);
        $endpoint->set_params($params);
        return $this->perform_request($endpoint);
    }
    /**
     * Get all messages in a memory.
     *
     * @param array{memory_id?: string, max_results?: int, next_token?: int, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - memory_id:
     * - max_results:
     * - next_token:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_all_messages(array $params = [])
    {
        $memory_id = $this->extract_argument($params, 'memory_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_All_Messages::class);
        $endpoint->set_params($params);
        $endpoint->set_memory_id($memory_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Get tools.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_all_tools(array $params = [])
    {
        $endpoint = $this->endpoint_factory->get_endpoint(Get_All_Tools::class);
        $endpoint->set_params($params);
        return $this->perform_request($endpoint);
    }
    /**
     * Retrieves a controller.
     *
     * @param array{model_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - model_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_controller(array $params = [])
    {
        $model_id = $this->extract_argument($params, 'model_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Controller::class);
        $endpoint->set_params($params);
        $endpoint->set_model_id($model_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Get a memory.
     *
     * @param array{memory_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - memory_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_memory(array $params = [])
    {
        $memory_id = $this->extract_argument($params, 'memory_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Memory::class);
        $endpoint->set_params($params);
        $endpoint->set_memory_id($memory_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Get a memory container.
     *
     * @param array{memory_container_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - memory_container_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_memory_container(array $params = [])
    {
        $memory_container_id = $this->extract_argument($params, 'memory_container_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Memory_Container::class);
        $endpoint->set_params($params);
        $endpoint->set_memory_container_id($memory_container_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Get a message.
     *
     * @param array{message_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - message_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_message(array $params = [])
    {
        $message_id = $this->extract_argument($params, 'message_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Message::class);
        $endpoint->set_params($params);
        $endpoint->set_message_id($message_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Get a message traces.
     *
     * @param array{message_id?: string, max_results?: int, next_token?: int, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - message_id:
     * - max_results:
     * - next_token:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_message_traces(array $params = [])
    {
        $message_id = $this->extract_argument($params, 'message_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Message_Traces::class);
        $endpoint->set_params($params);
        $endpoint->set_message_id($message_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Retrieves a model group.
     *
     * @param array{model_group_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - model_group_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_model_group(array $params = [])
    {
        $model_group_id = $this->extract_argument($params, 'model_group_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Model_Group::class);
        $endpoint->set_params($params);
        $endpoint->set_model_group_id($model_group_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Get a profile.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function get_profile(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Profile::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Get a profile models.
     *
     * @param array{model_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - model_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function get_profile_models(array $params = [])
    {
        $model_id = $this->extract_argument($params, 'model_id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Profile_Models::class);
        $endpoint->set_params($params);
        $endpoint->set_model_id($model_id);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Get a profile tasks.
     *
     * @param array{task_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - task_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function get_profile_tasks(array $params = [])
    {
        $task_id = $this->extract_argument($params, 'task_id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Profile_Tasks::class);
        $endpoint->set_params($params);
        $endpoint->set_task_id($task_id);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Get stats.
     *
     * @param array{node_id?: string, stat?: mixed, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - node_id:
     * - stat:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_stats(array $params = [])
    {
        $node_id = $this->extract_argument($params, 'node_id');
        $stat = $this->extract_argument($params, 'stat');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Stats::class);
        $endpoint->set_params($params);
        $endpoint->set_node_id($node_id);
        $endpoint->set_stat($stat);
        return $this->perform_request($endpoint);
    }
    /**
     * Retrieves a task.
     *
     * @param array{id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - id: (Required)
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_task(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Task::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        return $this->perform_request($endpoint);
    }
    /**
     * Get tools.
     *
     * @param array{tool_name?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - tool_name:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_tool(array $params = [])
    {
        $tool_name = $this->extract_argument($params, 'tool_name');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Tool::class);
        $endpoint->set_params($params);
        $endpoint->set_tool_name($tool_name);
        return $this->perform_request($endpoint);
    }
    /**
     * Deploys a model.
     *
     * @param array{model_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - model_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function load_model(array $params = [])
    {
        $model_id = $this->extract_argument($params, 'model_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Load_Model::class);
        $endpoint->set_params($params);
        $endpoint->set_model_id($model_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Predicts a model.
     *
     * @param array{model_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - model_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function predict_model(array $params = [])
    {
        $model_id = $this->extract_argument($params, 'model_id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Predict_Model::class);
        $endpoint->set_params($params);
        $endpoint->set_model_id($model_id);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Predicts a model in streaming mode.
     *
     * @param array{model_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - model_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function predict_model_stream(array $params = [])
    {
        $model_id = $this->extract_argument($params, 'model_id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Predict_Model_Stream::class);
        $endpoint->set_params($params);
        $endpoint->set_model_id($model_id);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Register an agent.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function register_agents(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Register_Agents::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Registers a model.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function register_model(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Register_Model::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Registers a model group.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function register_model_group(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Register_Model_Group::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Registers model metadata.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function register_model_meta(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Register_Model_Meta::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Search for memories of a specific type within a memory container.
     *
     * @param array{memory_container_id?: string, type?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - memory_container_id:
     * - type:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function search_agentic_memory(array $params = [])
    {
        $memory_container_id = $this->extract_argument($params, 'memory_container_id');
        $type = $this->extract_argument($params, 'type');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Search_Agentic_Memory::class);
        $endpoint->set_params($params);
        $endpoint->set_memory_container_id($memory_container_id);
        $endpoint->set_type($type);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Search agents.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function search_agents(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Search_Agents::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Searches for standalone connectors.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function search_connectors(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Search_Connectors::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Search memory.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function search_memory(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Search_Memory::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Search memory containers.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function search_memory_container(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Search_Memory_Container::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Search messages.
     *
     * @param array{memory_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - memory_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function search_message(array $params = [])
    {
        $memory_id = $this->extract_argument($params, 'memory_id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Search_Message::class);
        $endpoint->set_params($params);
        $endpoint->set_memory_id($memory_id);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Searches for model groups.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function search_model_group(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Search_Model_Group::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Searches for models.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function search_models(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Search_Models::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Searches for tasks.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function search_tasks(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Search_Tasks::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Trains a model synchronously.
     *
     * @param array{algorithm_name?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - algorithm_name:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function train(array $params = [])
    {
        $algorithm_name = $this->extract_argument($params, 'algorithm_name');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Train::class);
        $endpoint->set_params($params);
        $endpoint->set_algorithm_name($algorithm_name);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Trains a model and predicts against the same training dataset.
     *
     * @param array{algorithm_name?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - algorithm_name:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function train_predict(array $params = [])
    {
        $algorithm_name = $this->extract_argument($params, 'algorithm_name');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Train_Predict::class);
        $endpoint->set_params($params);
        $endpoint->set_algorithm_name($algorithm_name);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Unloads a model.
     *
     * @param array{model_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - model_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function unload_model(array $params = [])
    {
        $model_id = $this->extract_argument($params, 'model_id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Unload_Model::class);
        $endpoint->set_params($params);
        $endpoint->set_model_id($model_id);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Update a specific memory by its type and ID.
     *
     * @param array{id?: string, memory_container_id?: string, type?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - id: (Required)
     * - memory_container_id:
     * - type:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function update_agentic_memory(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $memory_container_id = $this->extract_argument($params, 'memory_container_id');
        $type = $this->extract_argument($params, 'type');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Update_Agentic_Memory::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        $endpoint->set_memory_container_id($memory_container_id);
        $endpoint->set_type($type);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Updates a standalone connector.
     *
     * @param array{connector_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - connector_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function update_connector(array $params = [])
    {
        $connector_id = $this->extract_argument($params, 'connector_id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Update_Connector::class);
        $endpoint->set_params($params);
        $endpoint->set_connector_id($connector_id);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Updates a controller.
     *
     * @param array{model_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - model_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function update_controller(array $params = [])
    {
        $model_id = $this->extract_argument($params, 'model_id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Update_Controller::class);
        $endpoint->set_params($params);
        $endpoint->set_model_id($model_id);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Update a memory.
     *
     * @param array{memory_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - memory_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function update_memory(array $params = [])
    {
        $memory_id = $this->extract_argument($params, 'memory_id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Update_Memory::class);
        $endpoint->set_params($params);
        $endpoint->set_memory_id($memory_id);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Update a memory container.
     *
     * @param array{memory_container_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - memory_container_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function update_memory_container(array $params = [])
    {
        $memory_container_id = $this->extract_argument($params, 'memory_container_id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Update_Memory_Container::class);
        $endpoint->set_params($params);
        $endpoint->set_memory_container_id($memory_container_id);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Update a message.
     *
     * @param array{message_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - message_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function update_message(array $params = [])
    {
        $message_id = $this->extract_argument($params, 'message_id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Update_Message::class);
        $endpoint->set_params($params);
        $endpoint->set_message_id($message_id);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Updates a model.
     *
     * @param array{model_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - model_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function update_model(array $params = [])
    {
        $model_id = $this->extract_argument($params, 'model_id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Update_Model::class);
        $endpoint->set_params($params);
        $endpoint->set_model_id($model_id);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Uploads model chunk.
     *
     * @param array{chunk_number?: int, model_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - chunk_number:
     * - model_id:
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function upload_chunk(array $params = [])
    {
        $chunk_number = $this->extract_argument($params, 'chunk_number');
        $model_id = $this->extract_argument($params, 'model_id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Upload_Chunk::class);
        $endpoint->set_params($params);
        $endpoint->set_chunk_number($chunk_number);
        $endpoint->set_model_id($model_id);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Registers a model.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function upload_model(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Upload_Model::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * $params['body']             = (string) The body of the request (Required)
     *
     * @param array $params Associative array of parameters
     *
     * @return array
     *   The response.
     */
    public function create_connector(array $params = []): array
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Create_Connector::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * $params['connector_id'] = (string) The id of the connector (Required)
     *
     * @param array $params Associative array of parameters
     *
     * @return array
     *   The response.
     */
    public function delete_connector(array $params = []): array
    {
        $connector_id = $this->extract_argument($params, 'connector_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Connector::class);
        $endpoint->set_params($params);
        $endpoint->set_connector_id($connector_id);
        return $this->perform_request($endpoint);
    }
    /**
     * $params['model_id']       = (string) The id of the model (Required)
     * $params['body']           = (string) The body of the request
     *
     * @param array $params Associative array of parameters
     *
     * @return array
     *   The response.
     */
    public function deploy_model(array $params = []): array
    {
        $model_id = $this->extract_argument($params, 'model_id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Deploy_Model::class);
        $endpoint->set_params($params);
        $endpoint->set_model_id($model_id);
        if ($body) {
            $endpoint->set_body($body);
        }
        return $this->perform_request($endpoint);
    }
    /**
     * $params['id']             = (string) The id of the connector (Required)
     *
     * @param array $params Associative array of parameters
     *
     * @return array
     *   The response.
     */
    public function get_connector(array $params = []): array
    {
        $id = $this->extract_argument($params, 'id');
        $connector_id = $this->extract_argument($params, 'connector_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Connector::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        $endpoint->set_connector_id($connector_id);
        return $this->perform_request($endpoint);
    }
    /**
     * $params['body']             = (string) The body of the request
     *
     * @param array $params Associative array of parameters
     *
     * @return array
     *   The response.
     */
    public function get_connectors(array $params = []): array
    {
        if (!isset($params['body'])) {
            $params['body'] = ['query' => ['match_all' => new \Std_Class()], 'size' => 1000];
        }
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Connectors::class);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * $params['body']             = (string) The body of the request
     *
     * @param array $params Associative array of parameters
     *
     * @return array
     *   The response.
     */
    public function get_model_groups(array $params = []): array
    {
        if (!isset($params['body'])) {
            $params['body'] = ['query' => ['match_all' => new \Std_Class()], 'size' => 1000];
        }
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Model_Groups::class);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * $params['id']             = (string) The id of the model (Required)
     *
     * @param array $params Associative array of parameters
     *
     * @return array
     *   The response.
     */
    public function get_model(array $params = []): array
    {
        $id = $this->extract_argument($params, 'id');
        $model_id = $this->extract_argument($params, 'model_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Model::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        $endpoint->set_model_id($model_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Proxy function to getModels() to prevent BC break.
     * This API will be removed in a future version. Use 'searchModels' API instead.
     */
    public function get_models(array $params = [])
    {
        if (!isset($params['body'])) {
            $params['body'] = ['query' => ['match_all' => new \Std_Class()], 'size' => 1000];
        }
        return $this->search_models($params);
    }
    /**
     * $params['id']             = (string) The id of the model (Required)
     * $params['body']           = (string) The body of the request
     *
     * @param array $params Associative array of parameters
     *
     * @return array
     *   The response.
     */
    public function predict(array $params = []): array
    {
        $id = $this->extract_argument($params, 'id');
        $body = $this->extract_argument($params, 'body');
        $algorithm_name = $this->extract_argument($params, 'algorithm_name');
        $model_id = $this->extract_argument($params, 'model_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Predict::class);
        $endpoint->set_params($params)->set_id($id)->set_body($body)->set_algorithm_name($algorithm_name)->set_model_id($model_id);
        return $this->perform_request($endpoint);
    }
    /**
     * $params['model_id']       = (string) The id of the model (Required)
     * $params['body']           = (string) The body of the request
     *
     * @param array $params Associative array of parameters
     *
     * @return array
     *   The response.
     */
    public function undeploy_model(array $params = []): array
    {
        $model_id = $this->extract_argument($params, 'model_id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Undeploy_Model::class);
        $endpoint->set_params($params);
        $endpoint->set_model_id($model_id);
        if ($body) {
            $endpoint->set_body($body);
        }
        return $this->perform_request($endpoint);
    }
    /**
     * $params['id']             = (string) The id of the model group (Required)
     * $params['body']           = (array) The body of the request (Required)
     *
     * @param array $params Associative array of parameters
     *
     * @return array
     *   The response.
     */
    public function update_model_group(array $params = []): array
    {
        $id = $this->extract_argument($params, 'id');
        $model_group_id = $this->extract_argument($params, 'model_group_id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Update_Model_Group::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        $endpoint->set_id($id);
        $endpoint->set_model_group_id($model_group_id);
        return $this->perform_request($endpoint);
    }
}