<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Namespaces;

use Open_Search\Endpoints\Observability\Create_Object;
use Open_Search\Endpoints\Observability\Delete_Object;
use Open_Search\Endpoints\Observability\Delete_Objects;
use Open_Search\Endpoints\Observability\Get_Localstats;
use Open_Search\Endpoints\Observability\Get_Object;
use Open_Search\Endpoints\Observability\List_Objects;
use Open_Search\Endpoints\Observability\Update_Object;
/**
 * Class ObservabilityNamespace
 *
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Observability_Namespace extends Abstract_Namespace
{
    /**
     * Creates a new observability object.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function create_object(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Create_Object::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Deletes specific observability object specified by ID.
     *
     * @param array{object_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - object_id: The ID of the observability object to delete.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete_object(array $params = [])
    {
        $object_id = $this->extract_argument($params, 'object_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Object::class);
        $endpoint->set_params($params);
        $endpoint->set_object_id($object_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Deletes specific observability objects specified by ID or a list of IDs.
     *
     * @param array{objectId?: string, objectIdList?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - objectId: The ID of a single observability object to delete.
     * - objectIdList: A comma-separated list of observability object IDs to delete.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete_objects(array $params = [])
    {
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Objects::class);
        $endpoint->set_params($params);
        return $this->perform_request($endpoint);
    }
    /**
     * Retrieves local stats of all observability objects.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_localstats(array $params = [])
    {
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Localstats::class);
        $endpoint->set_params($params);
        return $this->perform_request($endpoint);
    }
    /**
     * Retrieves specific observability object specified by ID.
     *
     * @param array{object_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - object_id: The ID of the observability object to retrieve.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_object(array $params = [])
    {
        $object_id = $this->extract_argument($params, 'object_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Object::class);
        $endpoint->set_params($params);
        $endpoint->set_object_id($object_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Retrieves list of all observability objects.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function list_objects(array $params = [])
    {
        $endpoint = $this->endpoint_factory->get_endpoint(List_Objects::class);
        $endpoint->set_params($params);
        return $this->perform_request($endpoint);
    }
    /**
     * Updates an existing observability object.
     *
     * @param array{object_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - object_id: The ID of the observability object to update.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function update_object(array $params = [])
    {
        $object_id = $this->extract_argument($params, 'object_id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Update_Object::class);
        $endpoint->set_params($params);
        $endpoint->set_object_id($object_id);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
}