<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Namespaces;

use Open_Search\Endpoints\Query\Datasource_Delete;
use Open_Search\Endpoints\Query\Datasource_Retrieve;
use Open_Search\Endpoints\Query\Datasources_Create;
use Open_Search\Endpoints\Query\Datasources_List;
use Open_Search\Endpoints\Query\Datasources_Update;
/**
 * Class QueryNamespace
 *
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Query_Namespace extends Abstract_Namespace
{
    /**
     * Deletes a specific data source by name.
     *
     * @param array{datasource_name?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - datasource_name: The name of the data source to delete.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function datasource_delete(array $params = [])
    {
        $datasource_name = $this->extract_argument($params, 'datasource_name');
        $endpoint = $this->endpoint_factory->get_endpoint(Datasource_Delete::class);
        $endpoint->set_params($params);
        $endpoint->set_datasource_name($datasource_name);
        return $this->perform_request($endpoint);
    }
    /**
     * Retrieves a specific data source by name.
     *
     * @param array{datasource_name?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - datasource_name: The name of the data source to retrieve.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function datasource_retrieve(array $params = [])
    {
        $datasource_name = $this->extract_argument($params, 'datasource_name');
        $endpoint = $this->endpoint_factory->get_endpoint(Datasource_Retrieve::class);
        $endpoint->set_params($params);
        $endpoint->set_datasource_name($datasource_name);
        return $this->perform_request($endpoint);
    }
    /**
     * Creates a new query data source.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function datasources_create(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Datasources_Create::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Retrieves a list of all available data sources.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function datasources_list(array $params = [])
    {
        $endpoint = $this->endpoint_factory->get_endpoint(Datasources_List::class);
        $endpoint->set_params($params);
        return $this->perform_request($endpoint);
    }
    /**
     * Updates an existing query data source.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function datasources_update(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Datasources_Update::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
}