<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Namespaces;

use Open_Search\Endpoints\Replication\Autofollow_Stats;
use Open_Search\Endpoints\Replication\Create_Replication_Rule;
use Open_Search\Endpoints\Replication\Delete_Replication_Rule;
use Open_Search\Endpoints\Replication\Follower_Stats;
use Open_Search\Endpoints\Replication\Leader_Stats;
use Open_Search\Endpoints\Replication\Pause;
use Open_Search\Endpoints\Replication\Resume;
use Open_Search\Endpoints\Replication\Start;
use Open_Search\Endpoints\Replication\Status;
use Open_Search\Endpoints\Replication\Stop;
use Open_Search\Endpoints\Replication\Update_Settings;
/**
 * Class ReplicationNamespace
 *
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Replication_Namespace extends Abstract_Namespace
{
    /**
     * Retrieves information about any auto-follow activity and any replication rules configured on the specified cluster.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function autofollow_stats(array $params = [])
    {
        $endpoint = $this->endpoint_factory->get_endpoint(Autofollow_Stats::class);
        $endpoint->set_params($params);
        return $this->perform_request($endpoint);
    }
    /**
     * Automatically starts the replication on indexes matching a specified pattern.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body: (Required)
     * @return array
     */
    public function create_replication_rule(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Create_Replication_Rule::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Deletes the specified replication rule.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body: (Required)
     * @return array
     */
    public function delete_replication_rule(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Replication_Rule::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Retrieves information about any follower (syncing) indexes on a specified cluster.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function follower_stats(array $params = [])
    {
        $endpoint = $this->endpoint_factory->get_endpoint(Follower_Stats::class);
        $endpoint->set_params($params);
        return $this->perform_request($endpoint);
    }
    /**
     * Retrieves information about any replicated leader indexes on a specified cluster.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function leader_stats(array $params = [])
    {
        $endpoint = $this->endpoint_factory->get_endpoint(Leader_Stats::class);
        $endpoint->set_params($params);
        return $this->perform_request($endpoint);
    }
    /**
     * Pauses the replication of the leader index.
     *
     * @param array{index?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - index: The name of the data stream, index, or index alias to perform bulk actions on.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body: (Required)
     * @return array
     */
    public function pause(array $params = [])
    {
        $index = $this->extract_argument($params, 'index');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Pause::class);
        $endpoint->set_params($params);
        $endpoint->set_index($index);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Resumes replication of the leader index.
     *
     * @param array{index?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - index: The name of the data stream, index, or index alias to perform bulk actions on.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body: (Required)
     * @return array
     */
    public function resume(array $params = [])
    {
        $index = $this->extract_argument($params, 'index');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Resume::class);
        $endpoint->set_params($params);
        $endpoint->set_index($index);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Initiates the replication of an index from the leader cluster to the follower cluster.
     *
     * @param array{index?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - index: The name of the data stream, index, or index alias to perform bulk actions on.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body: (Required)
     * @return array
     */
    public function start(array $params = [])
    {
        $index = $this->extract_argument($params, 'index');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Start::class);
        $endpoint->set_params($params);
        $endpoint->set_index($index);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Retrieves the the status of an index replication.
     *
     * @param array{index?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - index: The name of the data stream, index, or index alias to perform bulk actions on.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function status(array $params = [])
    {
        $index = $this->extract_argument($params, 'index');
        $endpoint = $this->endpoint_factory->get_endpoint(Status::class);
        $endpoint->set_params($params);
        $endpoint->set_index($index);
        return $this->perform_request($endpoint);
    }
    /**
     * Terminates the replication and converts the follower index to a standard index.
     *
     * @param array{index?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - index: The name of the data stream, index, or index alias to perform bulk actions on.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body: (Required)
     * @return array
     */
    public function stop(array $params = [])
    {
        $index = $this->extract_argument($params, 'index');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Stop::class);
        $endpoint->set_params($params);
        $endpoint->set_index($index);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Updates any settings on the follower index.
     *
     * @param array{index?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - index: The name of the data stream, index, or index alias to perform bulk actions on.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body: (Required)
     * @return array
     */
    public function update_settings(array $params = [])
    {
        $index = $this->extract_argument($params, 'index');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Update_Settings::class);
        $endpoint->set_params($params);
        $endpoint->set_index($index);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
}