<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Namespaces;

use Open_Search\Endpoints\Rollups\Delete;
use Open_Search\Endpoints\Rollups\Explain;
use Open_Search\Endpoints\Rollups\Get;
use Open_Search\Endpoints\Rollups\Put;
use Open_Search\Endpoints\Rollups\Start;
use Open_Search\Endpoints\Rollups\Stop;
/**
 * Class RollupsNamespace
 *
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Rollups_Namespace extends Abstract_Namespace
{
    /**
     * Deletes an index rollup job configuration.
     *
     * @param array{id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - id: The ID of the rollup job. (Required)
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        return $this->perform_request($endpoint);
    }
    /**
     * Retrieves the execution status information for an index rollup job.
     *
     * @param array{id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - id: The ID of the rollup job. (Required)
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function explain(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $endpoint = $this->endpoint_factory->get_endpoint(Explain::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        return $this->perform_request($endpoint);
    }
    /**
     * Retrieves an index rollup job configuration by ID.
     *
     * @param array{id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - id: The ID of the rollup job. (Required)
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $endpoint = $this->endpoint_factory->get_endpoint(Get::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        return $this->perform_request($endpoint);
    }
    /**
     * Creates or updates an index rollup job configuration.
     *
     * @param array{id?: string, if_primary_term?: int|float, if_seq_no?: int, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - id: The ID of the rollup job. (Required)
     * - if_primary_term: Only performs the operation if the document has the specified primary term.
     * - if_seq_no: Only performs the operation if the document has the specified sequence number.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function put(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Put::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Starts the execution of an index rollup job.
     *
     * @param array{id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - id: The ID of the rollup job. (Required)
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function start(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $endpoint = $this->endpoint_factory->get_endpoint(Start::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        return $this->perform_request($endpoint);
    }
    /**
     * Stops the execution of an index rollup job.
     *
     * @param array{id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - id: The ID of the rollup job. (Required)
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function stop(array $params = [])
    {
        $id = $this->extract_argument($params, 'id');
        $endpoint = $this->endpoint_factory->get_endpoint(Stop::class);
        $endpoint->set_params($params);
        $endpoint->set_id($id);
        return $this->perform_request($endpoint);
    }
}