<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Namespaces;

use Open_Search\Endpoints\Search_Relevance\Delete_Experiments;
use Open_Search\Endpoints\Search_Relevance\Delete_Judgments;
use Open_Search\Endpoints\Search_Relevance\Delete_Query_Sets;
use Open_Search\Endpoints\Search_Relevance\Delete_Scheduled_Experiments;
use Open_Search\Endpoints\Search_Relevance\Delete_Search_Configurations;
use Open_Search\Endpoints\Search_Relevance\Get_Experiments;
use Open_Search\Endpoints\Search_Relevance\Get_Judgments;
use Open_Search\Endpoints\Search_Relevance\Get_Node_Stats;
use Open_Search\Endpoints\Search_Relevance\Get_Query_Sets;
use Open_Search\Endpoints\Search_Relevance\Get_Scheduled_Experiments;
use Open_Search\Endpoints\Search_Relevance\Get_Search_Configurations;
use Open_Search\Endpoints\Search_Relevance\Get_Stats;
use Open_Search\Endpoints\Search_Relevance\Post_Query_Sets;
use Open_Search\Endpoints\Search_Relevance\Post_Scheduled_Experiments;
use Open_Search\Endpoints\Search_Relevance\Put_Experiments;
use Open_Search\Endpoints\Search_Relevance\Put_Judgments;
use Open_Search\Endpoints\Search_Relevance\Put_Query_Sets;
use Open_Search\Endpoints\Search_Relevance\Put_Search_Configurations;
/**
 * Class SearchRelevanceNamespace
 *
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Search_Relevance_Namespace extends Abstract_Namespace
{
    /**
     * Deletes a specified experiment.
     *
     * @param array{experiment_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - experiment_id: The experiment id
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete_experiments(array $params = [])
    {
        $experiment_id = $this->extract_argument($params, 'experiment_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Experiments::class);
        $endpoint->set_params($params);
        $endpoint->set_experiment_id($experiment_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Deletes a specified judgment.
     *
     * @param array{judgment_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - judgment_id: The judgment id
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete_judgments(array $params = [])
    {
        $judgment_id = $this->extract_argument($params, 'judgment_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Judgments::class);
        $endpoint->set_params($params);
        $endpoint->set_judgment_id($judgment_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Deletes a query set.
     *
     * @param array{query_set_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - query_set_id: The query set id
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete_query_sets(array $params = [])
    {
        $query_set_id = $this->extract_argument($params, 'query_set_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Query_Sets::class);
        $endpoint->set_params($params);
        $endpoint->set_query_set_id($query_set_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Deletes a specified scheduled experiment.
     *
     * @param array{experiment_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - experiment_id: The experiment id
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete_scheduled_experiments(array $params = [])
    {
        $experiment_id = $this->extract_argument($params, 'experiment_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Scheduled_Experiments::class);
        $endpoint->set_params($params);
        $endpoint->set_experiment_id($experiment_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Deletes a specified search configuration.
     *
     * @param array{search_configuration_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - search_configuration_id: The search configuration id
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete_search_configurations(array $params = [])
    {
        $search_configuration_id = $this->extract_argument($params, 'search_configuration_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Search_Configurations::class);
        $endpoint->set_params($params);
        $endpoint->set_search_configuration_id($search_configuration_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Gets experiments.
     *
     * @param array{experiment_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - experiment_id: The experiment id
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_experiments(array $params = [])
    {
        $experiment_id = $this->extract_argument($params, 'experiment_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Experiments::class);
        $endpoint->set_params($params);
        $endpoint->set_experiment_id($experiment_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Gets judgments.
     *
     * @param array{judgment_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - judgment_id: The judgment id
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_judgments(array $params = [])
    {
        $judgment_id = $this->extract_argument($params, 'judgment_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Judgments::class);
        $endpoint->set_params($params);
        $endpoint->set_judgment_id($judgment_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Gets stats by node.
     *
     * @param array{node_id?: string, stat?: string, flat_stat_paths?: string, include_all_nodes?: string, include_individual_nodes?: string, include_info?: string, include_metadata?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - node_id: The node id
     * - stat: The statistic to return
     * - flat_stat_paths: Requests flattened stat paths as keys
     * - include_all_nodes: Whether to include all nodes
     * - include_individual_nodes: Whether to include individual nodes
     * - include_info: Whether to include info
     * - include_metadata: Whether to include metadata
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_node_stats(array $params = [])
    {
        $node_id = $this->extract_argument($params, 'node_id');
        $stat = $this->extract_argument($params, 'stat');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Node_Stats::class);
        $endpoint->set_params($params);
        $endpoint->set_node_id($node_id);
        $endpoint->set_stat($stat);
        return $this->perform_request($endpoint);
    }
    /**
     * Lists the current query sets available.
     *
     * @param array{query_set_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - query_set_id: The query set id
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_query_sets(array $params = [])
    {
        $query_set_id = $this->extract_argument($params, 'query_set_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Query_Sets::class);
        $endpoint->set_params($params);
        $endpoint->set_query_set_id($query_set_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Gets the scheduled experiments.
     *
     * @param array{experiment_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - experiment_id: The experiment id
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_scheduled_experiments(array $params = [])
    {
        $experiment_id = $this->extract_argument($params, 'experiment_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Scheduled_Experiments::class);
        $endpoint->set_params($params);
        $endpoint->set_experiment_id($experiment_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Gets the search configurations.
     *
     * @param array{search_configuration_id?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - search_configuration_id: The search configuration id
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_search_configurations(array $params = [])
    {
        $search_configuration_id = $this->extract_argument($params, 'search_configuration_id');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Search_Configurations::class);
        $endpoint->set_params($params);
        $endpoint->set_search_configuration_id($search_configuration_id);
        return $this->perform_request($endpoint);
    }
    /**
     * Gets stats.
     *
     * @param array{stat?: string, flat_stat_paths?: string, include_all_nodes?: string, include_individual_nodes?: string, include_info?: string, include_metadata?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - stat: The statistic to return
     * - flat_stat_paths: Requests flattened stat paths as keys
     * - include_all_nodes: Whether to include all nodes
     * - include_individual_nodes: Whether to include individual nodes
     * - include_info: Whether to include info
     * - include_metadata: Whether to include metadata
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_stats(array $params = [])
    {
        $stat = $this->extract_argument($params, 'stat');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Stats::class);
        $endpoint->set_params($params);
        $endpoint->set_stat($stat);
        return $this->perform_request($endpoint);
    }
    /**
     * Creates a new query set by sampling queries from the user behavior data.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function post_query_sets(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Post_Query_Sets::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Creates a scheduled experiment.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function post_scheduled_experiments(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Post_Scheduled_Experiments::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Creates an experiment.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function put_experiments(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Put_Experiments::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Creates a judgment.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function put_judgments(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Put_Judgments::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Creates a new query set by uploading manually.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function put_query_sets(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Put_Query_Sets::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Creates a search configuration.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function put_search_configurations(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Put_Search_Configurations::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
}