<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Namespaces;

use Open_Search\Endpoints\Sm\Create_Policy;
use Open_Search\Endpoints\Sm\Delete_Policy;
use Open_Search\Endpoints\Sm\Explain_Policy;
use Open_Search\Endpoints\Sm\Get_Policies;
use Open_Search\Endpoints\Sm\Get_Policy;
use Open_Search\Endpoints\Sm\Start_Policy;
use Open_Search\Endpoints\Sm\Stop_Policy;
use Open_Search\Endpoints\Sm\Update_Policy;
/**
 * Class SmNamespace
 *
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Sm_Namespace extends Abstract_Namespace
{
    /**
     * Creates a snapshot management policy.
     *
     * @param array{policy_name?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - policy_name: The name of the snapshot management policy to create.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function create_policy(array $params = [])
    {
        $policy_name = $this->extract_argument($params, 'policy_name');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Create_Policy::class);
        $endpoint->set_params($params);
        $endpoint->set_policy_name($policy_name);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Deletes a snapshot management policy.
     *
     * @param array{policy_name?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - policy_name: The name of the snapshot management policy to delete.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete_policy(array $params = [])
    {
        $policy_name = $this->extract_argument($params, 'policy_name');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Policy::class);
        $endpoint->set_params($params);
        $endpoint->set_policy_name($policy_name);
        return $this->perform_request($endpoint);
    }
    /**
     * Explains the state of the snapshot management policy.
     *
     * @param array{policy_name?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - policy_name: The name of the snapshot management policy to explain.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function explain_policy(array $params = [])
    {
        $policy_name = $this->extract_argument($params, 'policy_name');
        $endpoint = $this->endpoint_factory->get_endpoint(Explain_Policy::class);
        $endpoint->set_params($params);
        $endpoint->set_policy_name($policy_name);
        return $this->perform_request($endpoint);
    }
    /**
     * Retrieves all snapshot management policies with optional pagination and filtering.
     *
     * @param array{from?: int, queryString?: string, size?: int, sortField?: string, sortOrder?: mixed, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - from: The starting index from which to retrieve snapshot management policies. (Default: 0)
     * - queryString: The query string to filter the returned snapshot management policies.
     * - size: The number of snapshot management policies to return.
     * - sortField: The name of the field to sort the snapshot management policies by.
     * - sortOrder: The order to sort the snapshot management policies. (Options: asc, desc)
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_policies(array $params = [])
    {
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Policies::class);
        $endpoint->set_params($params);
        return $this->perform_request($endpoint);
    }
    /**
     * Retrieves a specific snapshot management policy by name.
     *
     * @param array{policy_name?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - policy_name: The name of the snapshot management policy to retrieve.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_policy(array $params = [])
    {
        $policy_name = $this->extract_argument($params, 'policy_name');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Policy::class);
        $endpoint->set_params($params);
        $endpoint->set_policy_name($policy_name);
        return $this->perform_request($endpoint);
    }
    /**
     * Starts a snapshot management policy.
     *
     * @param array{policy_name?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - policy_name: The name of the snapshot management policy to start.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function start_policy(array $params = [])
    {
        $policy_name = $this->extract_argument($params, 'policy_name');
        $endpoint = $this->endpoint_factory->get_endpoint(Start_Policy::class);
        $endpoint->set_params($params);
        $endpoint->set_policy_name($policy_name);
        return $this->perform_request($endpoint);
    }
    /**
     * Stops a snapshot management policy.
     *
     * @param array{policy_name?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - policy_name: The name of the snapshot management policy to stop.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function stop_policy(array $params = [])
    {
        $policy_name = $this->extract_argument($params, 'policy_name');
        $endpoint = $this->endpoint_factory->get_endpoint(Stop_Policy::class);
        $endpoint->set_params($params);
        $endpoint->set_policy_name($policy_name);
        return $this->perform_request($endpoint);
    }
    /**
     * Updates an existing snapshot management policy. Requires `if_seq_no` and `if_primary_term`.
     *
     * @param array{policy_name?: string, if_primary_term?: int, if_seq_no?: int, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - policy_name: The name of the snapshot management policy to update.
     * - if_primary_term: The primary term of the policy to update.
     * - if_seq_no: The sequence number of the policy to update.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function update_policy(array $params = [])
    {
        $policy_name = $this->extract_argument($params, 'policy_name');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Update_Policy::class);
        $endpoint->set_params($params);
        $endpoint->set_policy_name($policy_name);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
}