<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Namespaces;

use Open_Search\Endpoints\Sql\Close;
use Open_Search\Endpoints\Sql\Explain;
use Open_Search\Endpoints\Sql\Get_Stats;
use Open_Search\Endpoints\Sql\Post_Stats;
use Open_Search\Endpoints\Sql\Query;
use Open_Search\Endpoints\Sql\Settings;
/**
 * Class SqlNamespace
 *
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Sql_Namespace extends Abstract_Namespace
{
    /**
     * Closes an open cursor to free server-side resources.
     *
     * @param array{format?: string, sanitize?: bool, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - format: Specifies the response format (JSON or YAML).
     * - sanitize: Whether to escape special characters in the results. (Default: true)
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function close(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Close::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Retrieves performance metrics for the SQL plugin.
     *
     * @param array{format?: string, sanitize?: bool, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - format: Specifies the response format (JSON or YAML).
     * - sanitize: Whether to escape special characters in the results. (Default: true)
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_stats(array $params = [])
    {
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Stats::class);
        $endpoint->set_params($params);
        return $this->perform_request($endpoint);
    }
    /**
     * Retrieves filtered performance metrics for the SQL plugin.
     *
     * @param array{format?: string, sanitize?: bool, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - format: Specifies the response format (JSON or YAML).
     * - sanitize: Whether to escape special characters in the results. (Default: true)
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function post_stats(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Post_Stats::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Updates SQL plugin settings in the OpenSearch cluster configuration.
     *
     * @param array{format?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - format: Specifies the response format (JSON or YAML).
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body:
     * @return array
     */
    public function settings(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Settings::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * This API will be removed in a future version. Use 'close' API instead.
     *
     * $params['cursor'] = (string) The cursor given by the server
     *
     * @param array{'cursor': string} $params Associative array of parameters
     */
    public function close_cursor(array $params): array
    {
        $endpoint = $this->endpoint_factory->get_endpoint(Close::class);
        $endpoint->set_body(array_filter(['cursor' => $this->extract_argument($params, 'cursor')]));
        $endpoint->set_params($params);
        return $this->perform_request($endpoint);
    }
    /**
     * $params['query'] = (string) The SQL Query
     *
     * @param array{'query': string} $params Associative array of parameters
     * @return array
     *
     * Note: Use of query parameter is deprecated. Pass it in `body` instead.
     */
    public function explain(array $params): array
    {
        $body = $this->extract_argument($params, 'body') ?? [];
        $query = $this->extract_argument($params, 'query');
        $endpoint = $this->endpoint_factory->get_endpoint(Explain::class);
        $endpoint->set_body(array_merge($body, ['query' => $query]));
        $endpoint->set_params($params);
        return $this->perform_request($endpoint);
    }
    /**
     * $params['query'] = (string) The SQL Query
     * $params['format'] = (string) The response format
     * $params['cursor'] = (string) The cursor given by the server
     * $params['fetch_size'] = (int) The fetch size
     *
     * @param array{'query'?: string, 'cursor'?: string, 'fetch_size'?: int} $params Associative array of parameters
     * @return array
     *
     * Note: Use of `query`, `cursor` and `fetch_size` parameters is deprecated. Pass them in `body` instead.
     *
     */
    public function query(array $params): array
    {
        $endpoint = $this->endpoint_factory->get_endpoint(Query::class);
        $body = $this->extract_argument($params, 'body') ?? [];
        $endpoint->set_body(array_merge($body, array_filter(['query' => $this->extract_argument($params, 'query'), 'cursor' => $this->extract_argument($params, 'cursor'), 'fetch_size' => $this->extract_argument($params, 'fetch_size')])));
        $endpoint->set_params($params);
        return $this->perform_request($endpoint);
    }
}