<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Namespaces;

use Open_Search\Endpoints\Wlm\Create_Query_Group;
use Open_Search\Endpoints\Wlm\Delete_Query_Group;
use Open_Search\Endpoints\Wlm\Get_Query_Group;
use Open_Search\Endpoints\Wlm\Update_Query_Group;
/**
 * Class WlmNamespace
 *
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Wlm_Namespace extends Abstract_Namespace
{
    /**
     * Creates a new query group and sets the resource limits for the new query group.
     *
     * @param array{pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body: (Required)
     * @return array
     */
    public function create_query_group(array $params = [])
    {
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Create_Query_Group::class);
        $endpoint->set_params($params);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
    /**
     * Deletes the specified query group.
     *
     * @param array{name?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - name: The name of the query group.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function delete_query_group(array $params = [])
    {
        $name = $this->extract_argument($params, 'name');
        $endpoint = $this->endpoint_factory->get_endpoint(Delete_Query_Group::class);
        $endpoint->set_params($params);
        $endpoint->set_name($name);
        return $this->perform_request($endpoint);
    }
    /**
     * Retrieves the specified query group. If no query group is specified, all query groups in the cluster are retrieved.
     *
     * @param array{name?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed} $params
     * - name: The name of the query group.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * @return array
     */
    public function get_query_group(array $params = [])
    {
        $name = $this->extract_argument($params, 'name');
        $endpoint = $this->endpoint_factory->get_endpoint(Get_Query_Group::class);
        $endpoint->set_params($params);
        $endpoint->set_name($name);
        return $this->perform_request($endpoint);
    }
    /**
     * Updates the specified query group.
     *
     * @param array{name?: string, pretty?: bool, human?: bool, error_trace?: bool, source?: string, filter_path?: mixed, body?: mixed} $params
     * - name: The name of the query group.
     * - pretty: Whether to pretty-format the returned JSON response. (Default: false)
     * - human: Whether to return human-readable values for statistics. (Default: false)
     * - error_trace: Whether to include the stack trace of returned errors. (Default: false)
     * - source: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
     * - filter_path: A comma-separated list of filters used to filter the response. Use wildcards to match any field or part of a field's name. To exclude fields, use `-`.
     * - body: (Required)
     * @return array
     */
    public function update_query_group(array $params = [])
    {
        $name = $this->extract_argument($params, 'name');
        $body = $this->extract_argument($params, 'body');
        $endpoint = $this->endpoint_factory->get_endpoint(Update_Query_Group::class);
        $endpoint->set_params($params);
        $endpoint->set_name($name);
        $endpoint->set_body($body);
        return $this->perform_request($endpoint);
    }
}