<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Endpoints\Sm;

use Open_Search\Endpoints\Abstract_Endpoint;
use Open_Search\Exception\RuntimeException;
/**
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Start_Policy extends Abstract_Endpoint
{
    protected $policy_name;
    public function get_uri(): string
    {
        $policy_name = $this->policy_name ? rawurlencode((string) $this->policy_name) : null;
        if (isset($policy_name)) {
            return "/_plugins/_sm/policies/{$policy_name}/_start";
        }
        throw new RuntimeException('Missing parameter for the endpoint sm.start_policy');
    }
    public function get_param_whitelist(): array
    {
        return ['pretty', 'human', 'error_trace', 'source', 'filter_path'];
    }
    public function get_method(): string
    {
        return 'POST';
    }
    public function set_policy_name($policy_name): static
    {
        if (is_null($policy_name)) {
            return $this;
        }
        $this->policy_name = $policy_name;
        return $this;
    }
}