<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Endpoints\Observability;

use Open_Search\Endpoints\Abstract_Endpoint;
use Open_Search\Exception\RuntimeException;
/**
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Get_Object extends Abstract_Endpoint
{
    protected $object_id;
    public function get_uri(): string
    {
        $object_id = $this->object_id ? rawurlencode((string) $this->object_id) : null;
        if (isset($object_id)) {
            return "/_plugins/_observability/object/{$object_id}";
        }
        throw new RuntimeException('Missing parameter for the endpoint observability.get_object');
    }
    public function get_param_whitelist(): array
    {
        return ['pretty', 'human', 'error_trace', 'source', 'filter_path'];
    }
    public function get_method(): string
    {
        return 'GET';
    }
    public function set_object_id($object_id): static
    {
        if (is_null($object_id)) {
            return $this;
        }
        $this->object_id = $object_id;
        return $this;
    }
}