<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Endpoints\Knn;

use Open_Search\Endpoints\Abstract_Endpoint;
/**
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Train_Model extends Abstract_Endpoint
{
    protected $model_id;
    public function get_uri(): string
    {
        $model_id = $this->model_id ? rawurlencode((string) $this->model_id) : null;
        if (isset($model_id)) {
            return "/_plugins/_knn/models/{$model_id}/_train";
        }
        return '/_plugins/_knn/models/_train';
    }
    public function get_param_whitelist(): array
    {
        return ['preference', 'pretty', 'human', 'error_trace', 'source', 'filter_path'];
    }
    public function get_method(): string
    {
        return 'POST';
    }
    public function set_body($body): static
    {
        if (is_null($body)) {
            return $this;
        }
        $this->body = $body;
        return $this;
    }
    public function set_model_id($model_id): static
    {
        if (is_null($model_id)) {
            return $this;
        }
        $this->model_id = $model_id;
        return $this;
    }
}