<?php

declare (strict_types=1);
/**
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * OpenSearch PHP client
 *
 * @link      https://github.com/opensearch-project/opensearch-php/
 * @copyright Copyright (c) Elasticsearch B.V (https://www.elastic.co)
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 * @license   https://www.gnu.org/licenses/lgpl-2.1.html GNU Lesser General Public License, Version 2.1
 *
 * Licensed to Elasticsearch B.V under one or more agreements.
 * Elasticsearch B.V licenses this file to you under the Apache 2.0 License or
 * the GNU Lesser General Public License, Version 2.1, at your option.
 * See the LICENSE file in the project root for more information.
 */
namespace Open_Search\Endpoints\Dangling_Indices;

use Open_Search\Endpoints\Abstract_Endpoint;
use Open_Search\Exception\RuntimeException;
/**
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Import_Dangling_Index extends Abstract_Endpoint
{
    protected $index_uuid;
    public function get_uri(): string
    {
        $index_uuid = $this->index_uuid ? rawurlencode((string) $this->index_uuid) : null;
        if (isset($index_uuid)) {
            return "/_dangling/{$index_uuid}";
        }
        throw new RuntimeException('Missing parameter for the endpoint dangling_indices.import_dangling_index');
    }
    public function get_param_whitelist(): array
    {
        return ['accept_data_loss', 'cluster_manager_timeout', 'master_timeout', 'timeout', 'pretty', 'human', 'error_trace', 'source', 'filter_path'];
    }
    public function get_method(): string
    {
        return 'POST';
    }
    public function set_index_uuid($index_uuid): static
    {
        if (is_null($index_uuid)) {
            return $this;
        }
        $this->index_uuid = $index_uuid;
        return $this;
    }
    protected function get_param_deprecation(): array
    {
        return ['master_timeout' => 'cluster_manager_timeout'];
    }
}