<?php

declare (strict_types=1);
/**
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * OpenSearch PHP client
 *
 * @link      https://github.com/opensearch-project/opensearch-php/
 * @copyright Copyright (c) Elasticsearch B.V (https://www.elastic.co)
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 * @license   https://www.gnu.org/licenses/lgpl-2.1.html GNU Lesser General Public License, Version 2.1
 *
 * Licensed to Elasticsearch B.V under one or more agreements.
 * Elasticsearch B.V licenses this file to you under the Apache 2.0 License or
 * the GNU Lesser General Public License, Version 2.1, at your option.
 * See the LICENSE file in the project root for more information.
 */
namespace Open_Search\Endpoints\Cat;

use Open_Search\Endpoints\Abstract_Endpoint;
/**
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Thread_Pool extends Abstract_Endpoint
{
    protected $thread_pool_patterns;
    public function get_uri(): string
    {
        $thread_pool_patterns = $this->thread_pool_patterns ? rawurlencode((string) $this->thread_pool_patterns) : null;
        if (isset($thread_pool_patterns)) {
            return "/_cat/thread_pool/{$thread_pool_patterns}";
        }
        return '/_cat/thread_pool';
    }
    public function get_param_whitelist(): array
    {
        return ['cluster_manager_timeout', 'format', 'h', 'help', 'local', 'master_timeout', 's', 'size', 'v', 'pretty', 'human', 'error_trace', 'source', 'filter_path'];
    }
    public function get_method(): string
    {
        return 'GET';
    }
    public function set_thread_pool_patterns($thread_pool_patterns): static
    {
        if (!isset($thread_pool_patterns)) {
            return $this;
        }
        if (is_array($thread_pool_patterns) === true) {
            $thread_pool_patterns = implode(',', $thread_pool_patterns);
        }
        $this->thread_pool_patterns = rawurlencode((string) $thread_pool_patterns);
        return $this;
    }
    protected function get_param_deprecation(): array
    {
        return ['master_timeout' => 'cluster_manager_timeout'];
    }
}