<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Endpoints\Ml;

use Open_Search\Endpoints\Abstract_Endpoint;
use Open_Search\Exception\RuntimeException;
/**
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Execute_Tool extends Abstract_Endpoint
{
    protected $tool_name;
    public function get_uri(): string
    {
        $tool_name = $this->tool_name ? rawurlencode((string) $this->tool_name) : null;
        if (isset($tool_name)) {
            return "/_plugins/_ml/tools/_execute/{$tool_name}";
        }
        throw new RuntimeException('Missing parameter for the endpoint ml.execute_tool');
    }
    public function get_param_whitelist(): array
    {
        return ['pretty', 'human', 'error_trace', 'source', 'filter_path'];
    }
    public function get_method(): string
    {
        return 'POST';
    }
    public function set_body($body): static
    {
        if (is_null($body)) {
            return $this;
        }
        $this->body = $body;
        return $this;
    }
    public function set_tool_name($tool_name): static
    {
        if (is_null($tool_name)) {
            return $this;
        }
        $this->tool_name = $tool_name;
        return $this;
    }
}