<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Endpoints\Ml;

use Open_Search\Endpoints\Abstract_Endpoint;
use Open_Search\Exception\RuntimeException;
/**
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Get_All_Messages extends Abstract_Endpoint
{
    protected $memory_id;
    public function get_uri(): string
    {
        $memory_id = $this->memory_id ? rawurlencode((string) $this->memory_id) : null;
        if (isset($memory_id)) {
            return "/_plugins/_ml/memory/{$memory_id}/messages";
        }
        throw new RuntimeException('Missing parameter for the endpoint ml.get_all_messages');
    }
    public function get_param_whitelist(): array
    {
        return ['max_results', 'next_token', 'pretty', 'human', 'error_trace', 'source', 'filter_path'];
    }
    public function get_method(): string
    {
        return 'GET';
    }
    public function set_memory_id($memory_id): static
    {
        if (is_null($memory_id)) {
            return $this;
        }
        $this->memory_id = $memory_id;
        return $this;
    }
}