<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Endpoints\Ml;

use Open_Search\Endpoints\Abstract_Endpoint;
use Open_Search\Exception\RuntimeException;
/**
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Get_Model_Group extends Abstract_Endpoint
{
    protected $model_group_id;
    public function get_uri(): string
    {
        $model_group_id = $this->model_group_id ? rawurlencode((string) $this->model_group_id) : null;
        if (isset($model_group_id)) {
            return "/_plugins/_ml/model_groups/{$model_group_id}";
        }
        throw new RuntimeException('Missing parameter for the endpoint ml.get_model_group');
    }
    public function get_param_whitelist(): array
    {
        return ['pretty', 'human', 'error_trace', 'source', 'filter_path'];
    }
    public function get_method(): string
    {
        return 'GET';
    }
    public function set_model_group_id($model_group_id): static
    {
        if (is_null($model_group_id)) {
            return $this;
        }
        $this->model_group_id = $model_group_id;
        return $this;
    }
}