<?php

declare (strict_types=1);
/**
 *  Copyright OpenSearch Contributors
 *   SPDX-License-Identifier: Apache-2.0
 *
 *   The OpenSearch Contributors require contributions made to
 *   this file be licensed under the Apache-2.0 license or a
 *   compatible open source license.
 */
namespace Open_Search\Endpoints\Ml;

use Open_Search\Endpoints\Abstract_Endpoint;
use Open_Search\Exception\RuntimeException;
/**
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Predict extends Abstract_Endpoint
{
    protected $algorithm_name;
    protected $model_id;
    public function get_uri(): string
    {
        $algorithm_name = $this->algorithm_name ? rawurlencode((string) $this->algorithm_name) : null;
        $model_id = $this->model_id ? rawurlencode((string) $this->model_id) : null;
        if (isset($algorithm_name) && isset($model_id)) {
            return "/_plugins/_ml/_predict/{$algorithm_name}/{$model_id}";
        }
        throw new RuntimeException('Missing parameter for the endpoint ml.predict');
    }
    public function get_param_whitelist(): array
    {
        return ['pretty', 'human', 'error_trace', 'source', 'filter_path'];
    }
    public function get_method(): string
    {
        return 'POST';
    }
    public function set_body($body): static
    {
        if (is_null($body)) {
            return $this;
        }
        $this->body = $body;
        return $this;
    }
    public function set_algorithm_name($algorithm_name): static
    {
        if (is_null($algorithm_name)) {
            return $this;
        }
        $this->algorithm_name = $algorithm_name;
        return $this;
    }
    public function set_model_id($model_id): static
    {
        if (is_null($model_id)) {
            return $this;
        }
        $this->model_id = $model_id;
        return $this;
    }
}