<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Endpoints\Geospatial;

use Open_Search\Endpoints\Abstract_Endpoint;
use Open_Search\Exception\RuntimeException;
/**
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Put_Ip2geo_Datasource_Settings extends Abstract_Endpoint
{
    protected $name;
    public function get_uri(): string
    {
        $name = $this->name ? rawurlencode((string) $this->name) : null;
        if (isset($name)) {
            return "/_plugins/geospatial/ip2geo/datasource/{$name}/_settings";
        }
        throw new RuntimeException('Missing parameter for the endpoint geospatial.put_ip2geo_datasource_settings');
    }
    public function get_param_whitelist(): array
    {
        return ['pretty', 'human', 'error_trace', 'source', 'filter_path'];
    }
    public function get_method(): string
    {
        return 'PUT';
    }
    public function set_body($body): static
    {
        if (is_null($body)) {
            return $this;
        }
        $this->body = $body;
        return $this;
    }
    public function set_name($name): static
    {
        if (is_null($name)) {
            return $this;
        }
        $this->name = $name;
        return $this;
    }
}