<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Endpoints\Ism;

use Open_Search\Endpoints\Abstract_Endpoint;
use Open_Search\Exception\RuntimeException;
/**
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Delete_Policy extends Abstract_Endpoint
{
    protected $policy_id;
    public function get_uri(): string
    {
        if (!isset($this->policy_id) || $this->policy_id === '') {
            throw new RuntimeException('policy_id is required for delete_policy');
        }
        $policy_id = rawurlencode((string) $this->policy_id);
        return "/_plugins/_ism/policies/{$policy_id}";
    }
    public function get_param_whitelist(): array
    {
        return ['pretty', 'human', 'error_trace', 'source', 'filter_path'];
    }
    public function get_method(): string
    {
        return 'DELETE';
    }
    public function set_policy_id($policy_id): static
    {
        if (is_null($policy_id)) {
            return $this;
        }
        $this->policy_id = $policy_id;
        return $this;
    }
}