<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Endpoints\Security;

use Open_Search\Endpoints\Abstract_Endpoint;
use Open_Search\Exception\RuntimeException;
/**
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Delete_Action_Group extends Abstract_Endpoint
{
    protected $action_group;
    public function get_uri(): string
    {
        if (!isset($this->action_group) || $this->action_group === '') {
            throw new RuntimeException('action_group is required for delete_action_group');
        }
        $action_group = rawurlencode((string) $this->action_group);
        return "/_plugins/_security/api/actiongroups/{$action_group}";
    }
    public function get_param_whitelist(): array
    {
        return ['pretty', 'human', 'error_trace', 'source', 'filter_path'];
    }
    public function get_method(): string
    {
        return 'DELETE';
    }
    public function set_action_group($action_group): static
    {
        if (is_null($action_group)) {
            return $this;
        }
        $this->action_group = $action_group;
        return $this;
    }
}