<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Endpoints\Security;

use Open_Search\Endpoints\Abstract_Endpoint;
use Open_Search\Exception\RuntimeException;
/**
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Delete_Tenant extends Abstract_Endpoint
{
    protected $tenant;
    public function get_uri(): string
    {
        if (!isset($this->tenant) || $this->tenant === '') {
            throw new RuntimeException('tenant is required for delete_tenant');
        }
        $tenant = rawurlencode((string) $this->tenant);
        return "/_plugins/_security/api/tenants/{$tenant}";
    }
    public function get_param_whitelist(): array
    {
        return ['pretty', 'human', 'error_trace', 'source', 'filter_path'];
    }
    public function get_method(): string
    {
        return 'DELETE';
    }
    public function set_tenant($tenant): static
    {
        if (is_null($tenant)) {
            return $this;
        }
        $this->tenant = $tenant;
        return $this;
    }
}