<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Endpoints\Security;

use Open_Search\Endpoints\Abstract_Endpoint;
use Open_Search\Exception\RuntimeException;
/**
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Get_Node_Certificates extends Abstract_Endpoint
{
    protected $node_id;
    public function get_uri(): string
    {
        $node_id = $this->node_id ? rawurlencode((string) $this->node_id) : null;
        if (isset($node_id)) {
            return "/_plugins/_security/api/certificates/{$node_id}";
        }
        throw new RuntimeException('Missing parameter for the endpoint security.get_node_certificates');
    }
    public function get_param_whitelist(): array
    {
        return ['cert_type', 'timeout', 'pretty', 'human', 'error_trace', 'source', 'filter_path'];
    }
    public function get_method(): string
    {
        return 'GET';
    }
    public function set_node_id($node_id): static
    {
        if (is_null($node_id)) {
            return $this;
        }
        $this->node_id = $node_id;
        return $this;
    }
}