<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Endpoints\Security;

use Open_Search\Endpoints\Abstract_Endpoint;
use Open_Search\Exception\RuntimeException;
/**
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Patch_Distinguished_Name extends Abstract_Endpoint
{
    protected $cluster_name;
    public function get_uri(): string
    {
        if (!isset($this->cluster_name) || $this->cluster_name === '') {
            throw new RuntimeException('cluster_name is required for patch_distinguished_name');
        }
        $cluster_name = rawurlencode((string) $this->cluster_name);
        return "/_plugins/_security/api/nodesdn/{$cluster_name}";
    }
    public function get_param_whitelist(): array
    {
        return ['pretty', 'human', 'error_trace', 'source', 'filter_path'];
    }
    public function get_method(): string
    {
        return 'PATCH';
    }
    public function set_body($body): static
    {
        if (is_null($body)) {
            return $this;
        }
        $this->body = $body;
        return $this;
    }
    public function set_cluster_name($cluster_name): static
    {
        if (is_null($cluster_name)) {
            return $this;
        }
        $this->cluster_name = $cluster_name;
        return $this;
    }
}