<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Endpoints\Flow_Framework;

use Open_Search\Endpoints\Abstract_Endpoint;
/**
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Create extends Abstract_Endpoint
{
    public function get_uri(): string
    {
        return '/_plugins/_flow_framework/workflow';
    }
    public function get_param_whitelist(): array
    {
        return ['provision', 'reprovision', 'update_fields', 'use_case', 'validation', 'pretty', 'human', 'error_trace', 'source', 'filter_path'];
    }
    public function get_method(): string
    {
        return 'POST';
    }
    public function set_body($body): static
    {
        if (is_null($body)) {
            return $this;
        }
        $this->body = $body;
        return $this;
    }
}