<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Endpoints\Search_Relevance;

use Open_Search\Endpoints\Abstract_Endpoint;
/**
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Get_Query_Sets extends Abstract_Endpoint
{
    protected $query_set_id;
    public function get_uri(): string
    {
        $query_set_id = $this->query_set_id ? rawurlencode((string) $this->query_set_id) : null;
        if (isset($query_set_id)) {
            return "/_plugins/_search_relevance/query_sets/{$query_set_id}";
        }
        return '/_plugins/_search_relevance/query_sets';
    }
    public function get_param_whitelist(): array
    {
        return ['pretty', 'human', 'error_trace', 'source', 'filter_path'];
    }
    public function get_method(): string
    {
        return 'GET';
    }
    public function set_query_set_id($query_set_id): static
    {
        if (is_null($query_set_id)) {
            return $this;
        }
        $this->query_set_id = $query_set_id;
        return $this;
    }
}