<?php

declare (strict_types=1);
/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
namespace Open_Search\Endpoints\Search_Relevance;

use Open_Search\Endpoints\Abstract_Endpoint;
/**
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class Get_Judgments extends Abstract_Endpoint
{
    protected $judgment_id;
    public function get_uri(): string
    {
        $judgment_id = $this->judgment_id ? rawurlencode((string) $this->judgment_id) : null;
        if (isset($judgment_id)) {
            return "/_plugins/_search_relevance/judgments/{$judgment_id}";
        }
        return '/_plugins/_search_relevance/judgments';
    }
    public function get_param_whitelist(): array
    {
        return ['pretty', 'human', 'error_trace', 'source', 'filter_path'];
    }
    public function get_method(): string
    {
        return 'GET';
    }
    public function set_judgment_id($judgment_id): static
    {
        if (is_null($judgment_id)) {
            return $this;
        }
        $this->judgment_id = $judgment_id;
        return $this;
    }
}